### ISSUE TITLE
[DataCap Application] IPFSPower Slingshot Restore Program

### ISSUE THREAD

**Issue by nj-steve** [filecoin-project/filecoin-plus-large-datasets#154] opened 2021-12-20 13:34 UTC
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: IPFSPower - Slingshot Restore
- Website / Social Media:ipfspower
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):80TiB
- On-chain address for first allocation: f3vtrnj3jlbsdw3u4jtnjf7v5gy7hwjyuaeuzj7aimudpwwuhsg654ytd5344rfi2gwam5jrceb7munoaknh6q

## Project details

Share a brief history of your project and organization.
```
Slingshot Restore is a dedicated effort by a selected group of clients and storage providers to recover the partial datasets that were lost as part of recent events on Dec 13, 2021.The Slingshot Restore Program is an initiative to restore ~12.5PiB of Slingshot data on Filecoin as quickly as possible.
IPFSPower is a distributed storage company of IPFS.And joined the race of filecoin in August 25, 2020.
```

What is the primary source of funding for this project?
```
The rewards of slingshot.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
I have participated in the Slingshot Restoreis Project with the name "shqingyan" in slack.
```

Where was the data in this dataset sourced from?
```
Slingshot Restore datasets.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
eg:
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00003.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00004.warc.gz
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Anytime in the day.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 500 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will send storage deal to at least 5 storage providers, the offline data process will be supported.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The storage providers that I send storage deals must at 3 different regions.And all providers must agree that they should store unsealed files and keep these data retrieved anytime.
```

How will you be distributing deals across storage providers?
```
I will send storage deals based on their ability to process data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have the resources/funding. And the community help me well.
```

**Comment by galen-mcandrew** [comment] 2021-12-20 23:50
## Multisig Notary requested
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 80TiB

**Comment by flyworker** [comment] 2021-12-21 04:00
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnb22m74elesbwxk3vbjbtqa74zibygr3x2subzfmg6exyflws3i 
#### Address 
> f3vtrnj3jlbsdw3u4jtnjf7v5gy7hwjyuaeuzj7aimudpwwuhsg654ytd5344rfi2gwam5jrceb7munoaknh6q
#### Datacap Allocated
> 25TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnb22m74elesbwxk3vbjbtqa74zibygr3x2subzfmg6exyflws3i

**Comment by Fenbushi-Filecoin** [comment] 2021-12-22 07:42
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceab7ufsa4wvrkwosn7yjqboldokx77kjbtdv4bsugziys5kpfazw4 
#### Address 
> f3vtrnj3jlbsdw3u4jtnjf7v5gy7hwjyuaeuzj7aimudpwwuhsg654ytd5344rfi2gwam5jrceb7munoaknh6q
#### Datacap Allocated
> 25TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceab7ufsa4wvrkwosn7yjqboldokx77kjbtdv4bsugziys5kpfazw4

**Comment by galen-mcandrew** [comment] 2021-12-22 17:11
@fabriziogianni7 Not sure the cause of the error label in this case either. Can you investigate?

Seeing 25 TiB at the client address, so I'm going to revert back to granted.

**Comment by filplus-checker** [comment] 2022-12-15 08:25
## DataCap and CID Checker Report[^1]
 - Organization: `IPFSPower - Slingshot Restore`
 - Client: `f3vtrnj3jlbsdw3u4jtnjf7v5gy7hwjyuaeuzj7aimudpwwuhsg654ytd5344rfi2gwam5jrceb7munoaknh6q`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01053413](https://filfox.info/en/address/f01053413) has sealed 84.75% of total datacap.

⚠️ 75.56% of total deal sealed by [f01981571](https://filfox.info/en/address/f01981571) are duplicate data.

⚠️ [f01981571](https://filfox.info/en/address/f01981571) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01053413](https://filfox.info/en/address/f01053413)`new`  | Hong Kong, Central and Western, HK |           3.91 TiB |     84.75% |    3.34 TiB |          14.40% |
| [f01981571](https://filfox.info/en/address/f01981571)`new`  |                            Unknown |         720.00 GiB |     15.25% |  176.00 GiB |          75.56% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/154/1671092706308.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         3.52 TiB |         4.61 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/154/1671092712851.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                   | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151) |            32.00 GiB |           1 | LDN v3 multisig |
| [f3upuh6u5tukt57szsnumwhludnldz5c4rcsgllbd<br/>4csdbnqfvdlta7clpr3svkof4o7j73iy7z6ju3ksl<br/>q7fq](https://filfox.info/en/address/f3upuh6u5tukt57szsnumwhludnldz5c4rcsgllbd4csdbnqfvdlta7clpr3svkof4o7j73iy7z6ju3kslq7fq) | Unknown                                                                                                       |           256.00 MiB |           1 |         Unknown |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by nj-steve** [comment] 2023-05-30 23:49
close this

**Closed** 2023-05-30 23:48 UTC
Labels: verified client, granted

**Comment by data-programs** [comment] 2023-08-08 12:01
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
