### ISSUE TITLE
[DataCap Application] Limradar

### ISSUE THREAD

**Issue by Pauline546** [filecoin-project/filecoin-plus-large-datasets#1595] opened 2023-02-09 10:50 UTC
### Data Owner Name

Shanghai Limradar Electronic Technology Co., Ltd 

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

https://www.limradar.com/

### Social Media

```text
Wechat: Limingruida
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1n36arb7rlf774wuzg35e5vaeedhzfsyjkixbgda

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shanghai Limradar was established in 2020. Our company focuses on radar detection, multi-sensor fusion, artificial intelligence traffic control and other technology research in the field of transportation, and provides relevant millimeter wave radar products around intelligent transportation, intelligent security, advanced assisted driving, rail safety and other applications.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data we store are radar test records used in various fields. Our company's product---Radar can be applied in several scenarios, including Smart Traffic, Smart Security, Advanced Driving Assistance, Track and traffic safety, etc. We have a large accumulation of data. The data we own is both public and private.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://drive.google.com/file/d/1cFc8Hq8_Wkg6jJwn7lU0pVq-eSG6w5hB/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment] 2023-02-09 15:36
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment] 2023-02-11 06:18
Can you provide more detailed informations about SPs you will cooperate with?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1595.

**Comment by Pauline546** [comment] 2023-02-13 06:15
@Sunnyiscoming SP has not been finalized yet from the SP side. But we will contact sps from different regions.
Here's the email, please check it.
![email](https://user-images.githubusercontent.com/112697444/218366219-93ef6789-415a-4a6f-99be-972225ae223b.png)

**Comment by lvschouwen** [comment] 2023-02-13 08:46
In you application you specify "The data we own is both public and private.".
Can you tell us how much of the requested datacap is public and how much is private?

FIL+ is ment to store public data. Private data can be stored in FIL-E.
If you application is a mix of both, I think it would be wise to move to FIL-E just to be sure private data does not get mixed in the FIL+ program and we can discussion about what has been stored later on.

@kevzak 
Tagging you as I would like to know your opinion about this.

**Comment by caoyoungyoung** [comment] 2023-02-13 09:45
The videos shared look like sensitive test data involving train and car, those data owned by the government? is it pubic accessible?

**Comment by kevzak** [comment] 2023-02-13 13:27
If both public and private, they could split into two separate applications. Or they can categorize all into E-Fil+ and go through full client/business/SP check.

**Comment by Pauline546** [comment] 2023-02-14 06:41
@lvschouwen @kevzak Thank you for your concern about our application! What I am saying in the application is that our company has both public and private data. But data we chose for datacap applying is public data. If our future storage in filecoin is very safe and convenient, we will consider participating in E-Fil+ next step!

**Comment by Pauline546** [comment] 2023-02-14 07:12
@caoyoungyoung Yes, data we choose are public data and owned by Limradar.

**Comment by Pauline546** [comment] 2023-02-15 03:19
@simonkim0515 @Sunnyiscoming Hi, can you please push my application into trigger?

**Comment by Sunnyiscoming** [comment] 2023-02-16 06:34
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1n36arb7rlf774wuzg35e5vaeedhzfsyjkixbgda

**Comment by Sunnyiscoming** [comment] 2023-02-16 06:34
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1n36arb7rlf774wuzg35e5vaeedhzfsyjkixbgda

**Comment by swatchliu** [comment] 2023-02-18 16:57
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatjfflll65mgmf4fyt5okpfb2j6vihmvlz4tl2capqpmo6sfgr6s 
#### Address 
> f1n36arb7rlf774wuzg35e5vaeedhzfsyjkixbgda
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> d85a0fb1-06e8-4b3a-bca1-3f5179620ccb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatjfflll65mgmf4fyt5okpfb2j6vihmvlz4tl2capqpmo6sfgr6s

**Comment by swatchliu** [comment] 2023-02-18 16:59
KYC is ok, Looks normal.

**Comment by cryptowhizzard** [comment] 2023-02-20 12:10
Sounds good. Thanks @swatchliu 

@Pauline546 can you list us the SP's where you want to store this data?

**Comment by swatchliu** [comment] 2023-02-21 07:39
Mr. Chen Lei and I had a 15-minute phone call today. The bullet point of KYC as follows:

1. Due to radar research and development, a large amount of scientific data and recording videos need to be stored.

2. The company's private cloud storage space has been used 82%, and it needs to continue to increase the cold preparation space.

3. The new storage method can bring the company's latest investment direction, which will be dealt with in the future.

**Comment by cryptowhizzard** [comment] 2023-02-21 13:17
Hi Eric,

Thanks for your time and effort you put into this. I am waiting for the list of SP's ( minimum of 4 for first allocation and different continents / organizations. ) .

**Comment by Pauline546** [comment] 2023-02-22 11:44
@swatchliu Nice chat! Thank you!
@cryptowhizzard Thank you for your patience. I am still in the process of contacting SP to join us. I will provide more information on the actual sealing process in the future.

**Comment by BobbyChoii** [comment] 2023-04-10 14:13
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7uy4xika7ny5diwuyg4y5sa3cp5te3rnnzhdy7knc677mvcu5gm 
#### Address 
> f1n36arb7rlf774wuzg35e5vaeedhzfsyjkixbgda
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7uy4xika7ny5diwuyg4y5sa3cp5te3rnnzhdy7knc677mvcu5gm

**Comment by data-programs** [comment] 2023-06-25 10:25
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has has been verified through [filplus.storage](https://filplus.storage)

**Comment by data-programs** [comment] 2023-06-27 19:32
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Pauline546** [comment] 2023-07-27 11:29
OK.

**Comment by cryptowhizzard** [comment] 2023-07-27 12:23
Tried to retrieve some data here but i got lots of errors.


--------------

cat 1595-f02031234-f02244750-46896534-baga6ea4seaqj2lpesnfbknwkcozwmejgslosukm25yx2gsauexodft5knwk6sly.log
2023-07-26T19:06:10.133+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02244750\",\"MinerPeer\":{\"Address\":\"f02244750\",\"ID\":\"12D3KooWHfCEGvQAdv7TR2tcQJtSwo8sQ6Da1Tdf6KzpsxxHY8ET\",\"PieceCID\":null}}"}
2023-07-26T19:06:10.133+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T19:08:00.633+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02244750\",\"MinerPeer\":{\"Address\":\"f02244750\",\"ID\":\"12D3KooWHfCEGvQAdv7TR2tcQJtSwo8sQ6Da1Tdf6KzpsxxHY8ET\",\"PieceCID\":null}}"}
2023-07-26T19:08:00.633+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T19:09:31.217+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02244750\",\"MinerPeer\":{\"Address\":\"f02244750\",\"ID\":\"12D3KooWHfCEGvQAdv7TR2tcQJtSwo8sQ6Da1Tdf6KzpsxxHY8ET\",\"PieceCID\":null}}"}
2023-07-26T19:09:31.217+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T19:10:07.783+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02244750\",\"MinerPeer\":{\"Address\":\"f02244750\",\"ID\":\"12D3KooWHfCEGvQAdv7TR2tcQJtSwo8sQ6Da1Tdf6KzpsxxHY8ET\",\"PieceCID\":null}}"}
2023-07-26T19:10:07.783+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T19:10:29.463+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02244750\",\"MinerPeer\":{\"Address\":\"f02244750\",\"ID\":\"12D3KooWHfCEGvQAdv7TR2tcQJtSwo8sQ6Da1Tdf6KzpsxxHY8ET\",\"PieceCID\":null}}"}
2023-07-26T19:10:29.463+0200	ERROR	retry	retry/retry.go:29	Failed after 5 attempts, last error: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
ERROR: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'

**Comment by cryptowhizzard** [comment] 2023-07-27 12:23
checker:manualTrigger

**Comment by Pauline546** [comment] 2023-08-10 09:16
Please keep my application.

**Comment by Pauline546** [comment] 2023-08-28 10:03
I'm looking for more SPs to stroe data. Can fil-plus team help open my application?

**Comment by clriesco** [comment] 2023-08-28 13:07
Removed stale label and reopened issue :)

**Comment by Pauline546** [comment] 2023-09-12 11:01
Please keep my application open.

**Comment by Pauline546** [comment] 2023-09-27 04:14
Please keep my application open.

**Comment by Pauline546** [comment] 2023-10-09 10:17
Please keep my application open.

**Comment by Pauline546** [comment] 2023-10-20 03:26
Please keep my application open.

**Comment by Sunnyiscoming** [comment] 2023-10-29 03:53
Hello, @Pauline546 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Casey-PG** [comment] 2023-10-31 02:21
checker:manualTrigger

**Comment by Pauline546** [comment] 2023-10-31 03:13
Hello @Sunnyiscoming , I have submitted the form.

**Comment by Casey-PG** [comment] 2023-10-31 04:19
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakqhh7pm3drv3wobmyrcedk226ofo575ilaqqive47h2bs6dazcw 
#### Address 
> f1n36arb7rlf774wuzg35e5vaeedhzfsyjkixbgda
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> d85a0fb1-06e8-4b3a-bca1-3f5179620ccb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakqhh7pm3drv3wobmyrcedk226ofo575ilaqqive47h2bs6dazcw

**Comment by Wengeding** [comment] 2023-10-31 04:32
have confirmed the status of the SP is ok,  please take care to keep.
![1698726712532](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/117442528/8ce110a4-e4e5-4063-8c67-3630114ef722)

**Comment by Wengeding** [comment] 2023-10-31 04:34
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag2yztfv6fdwwekwjlwhgez6nchg37mewo2mfe2vivk4gcay2ncc 
#### Address 
> f1n36arb7rlf774wuzg35e5vaeedhzfsyjkixbgda
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> d85a0fb1-06e8-4b3a-bca1-3f5179620ccb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag2yztfv6fdwwekwjlwhgez6nchg37mewo2mfe2vivk4gcay2ncc

**Comment by Pauline546** [comment] 2023-11-13 05:07
Yes

**Comment by herrehesse** [comment] 2023-11-14 09:29
checker:manualTrigger

**Comment by herrehesse** [comment] 2023-11-14 09:31
![Screenshot 2023-11-14 at 10 30 36](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/3e8b34a2-c6db-492f-a9b2-378960a1e6cb)

Selfdealing complete LDN, abusive notaries are signing.
Close this LDN @kevzak

**Comment by Filplus-govteam** [comment] 2023-11-22 18:53
SPs taking deals:
f01844232 | Dallas, Texas, USHawk Host Inc. | 119.53 TiB | 26.21% | 119.53 TiB | 0.00%
f0432570 | New York City, New York, USSingleHop LLC | 146.00 TiB | 32.02% | 146.00 TiB | 0.00%
f01844118 | New York City, New York, USSingleHop LLC | 48.75 TiB | 10.69% | 48.75 TiB | 0.00%
f01843994 | Dulles Town Center, Virginia, USSpeedyPage Ltd | 59.50 TiB | 13.05% | 59.50 TiB | 0.00%
f01788231 | Dulles Town Center, Virginia, USSpeedyPage Ltd | 59.00 TiB | 12.94% | 59.00 TiB | 0.00%
f02244750 | London, England, GBSpeedyPage Ltd | 12.00 TiB | 2.63% | 12.00 TiB | 0.00%
f01668new | London, England, GBSpeedyPage Ltd | 11.25 TiB | 2.47% | 11.25 TiB | 0.00%

SP list provided:
 f02244750 |  individual | London, England, GB | no | Charlie
f01844232 |  individual | Dallas, Texas, US | no | Lukas
f01668 |  individual | London, England, GB | no | Foster
f01843994 |  individual | Dulles Town Center, Virginia, US | no | hans
f01844118 | individual | New York City, New York, US | no | garry

No SP Entity info provided. All SPs under VPN. Please provide clear entity and distribution evidence. Closing until updated

**Closed by Filplus-govteam** 2023-11-22 18:53 UTC
Labels: ready to sign, start sign datacap, kyc verified
