### ISSUE TITLE
[DataCap Application] PUBLIC DATA-COVID-19 Genome Sequence Dataset [2/2]

### ISSUE THREAD

**Issue by nora310** [filecoin-project/filecoin-plus-large-datasets#1881] opened 2023-04-03 10:44 UTC
### Data Owner Name

National Library of Medicine (NLM)

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.ncbi.nlm.nih.gov/sra/docs/sra-aws-download/

### Social Media

```text
twitter-https://twitter.com/NIH_OSP
youtube-https://www.youtube.com/@nihofficeofsciencepolicy3005/videos
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ynotqzocbg2mzsnhtie6ozkyzxtkkdj2n3ooily

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
A centralized sequence repository for all records containing sequence associated with the novel corona virus (SARS-CoV-2) submitted to the National Center for Biotechnology Information (NCBI) Sequence Read Archive (SRA). Included are both the original sequences submitted by the principal investigator as well as SRA-processed sequences that require the SRA Toolkit for analysis. Additionally, submitter provided metadata included in associated BioSample and BioProject records is available alongside NCBI calculated data, such k-mer based taxonomy analysis results, contiguous assemblies (contigs) and associated statistics such as contig length, blast results for the assembled contigs, contig annotation, blast databases of contigs and their annotated peptides, and VCF files generated for each record relative to the SARS-CoV-2 RefSeq record. Finally, metadata is additionally made available in parquet format to facilitate search and filtering using the AWS Athena Service.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Genomic sequence reads of SARS-CoV-2 and related coronaviridae, organized by NCBI accession. Files in the sra-src folder are in FASTQ, BAM, or CRAM format (original submission); files in the run folder are in .sra format and require the SRA Toolkit; Metadata for sra-pub-sars-cov2 in an Athena-queryable format.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/ncbi-covid-19/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment] 2023-04-03 12:57
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1ynotqzocbg2mzsnhtie6ozkyzxtkkdj2n3ooily

**Comment by OlivierMolenkamp** [comment] 2023-04-10 14:25
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5h2io6qbjmjhltc6d2qzs7ce6s3v4gsrqi2mwnzfgcp4ey2lxtq 
#### Address 
> f1ynotqzocbg2mzsnhtie6ozkyzxtkkdj2n3ooily
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1fl5gjqv3xknuhka273jrsrkzqcumrp6idrnvgyi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5h2io6qbjmjhltc6d2qzs7ce6s3v4gsrqi2mwnzfgcp4ey2lxtq

**Comment by cryptowhizzard** [comment] 2023-04-12 12:52
@OlivierMolenkamp 

Can you let us (the community) know what due diligence has been done here for this client?
What is the data onboarding plan for this client? Where is he/she going to store the data and who is she? What is their internet capacity?
On what bases have you approved this application and why?

**Comment by nora310** [comment] 2023-06-20 03:57
Yes!

**Comment by nora310** [comment] 2023-07-05 02:05
Yes please!

**Comment by nora310** [comment] 2023-07-28 02:22
Yes please!

**Comment by cryptowhizzard** [comment] 2023-08-01 13:52
checker:manualTrigger

**Comment by nora310** [comment] 2023-08-13 16:19
Yes please!

**Comment by cryptowhizzard** [comment] 2023-08-31 13:52
Dear nora310,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqkbdulkm3b33kdqpukyhrkp62iofn6575yihph7vnpobkfewohyoi ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptowhizzard** [comment] 2023-08-31 13:53
Dear nora310,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqkbdulkm3b33kdqpukyhrkp62iofn6575yihph7vnpobkfewohyoi ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by nora310** [comment] 2023-09-18 10:35
Can not open this link.

> Dear nora310,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqkbdulkm3b33kdqpukyhrkp62iofn6575yihph7vnpobkfewohyoi ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by spaceT9** [comment] 2023-09-22 02:08
checker:manualTrigger

**Comment by nora310** [comment] 2023-10-03 05:06
Yes

**Comment by nora310** [comment] 2023-10-16 08:03
Keep open.

**Comment by nora310** [comment] 2023-10-27 11:17
Keep open.

**Comment by Sunnyiscoming** [comment] 2023-11-06 14:45
Hello, @nora310  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by nora310** [comment] 2023-11-07 05:55
Hello @Sunnyiscoming , I've finished.

**Comment by Wengeding** [comment] 2023-11-07 14:52
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxsynsnej6xfyyvbmk62ipenb2mzoekmpqctjxelmwnol3zrbv3e 
#### Address 
> f1ynotqzocbg2mzsnhtie6ozkyzxtkkdj2n3ooily
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 0bbcfae1-bef0-4eb9-8947-832c63c9e950
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxsynsnej6xfyyvbmk62ipenb2mzoekmpqctjxelmwnol3zrbv3e

**Comment by Holiday507** [comment] 2023-11-10 08:45
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgkhpqrduuht4bu5dw3vqyefb7tv2dl7gexhcgoquaswdqclr6ie 
#### Address 
> f1ynotqzocbg2mzsnhtie6ozkyzxtkkdj2n3ooily
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1sa3dp3a7fwirrsxjdthvzneo7rnjcrrfllsnjpq
#### Id
> 0bbcfae1-bef0-4eb9-8947-832c63c9e950
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgkhpqrduuht4bu5dw3vqyefb7tv2dl7gexhcgoquaswdqclr6ie

**Comment by TakiChain** [comment] 2023-11-11 04:28
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced66y3bwxu2s2jk3fnrgfquheppotiomrtqqazgryenprv5abio26 
#### Address 
> f1ynotqzocbg2mzsnhtie6ozkyzxtkkdj2n3ooily
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> ba54d45c-c604-4f29-acc0-682d2df76c1f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced66y3bwxu2s2jk3fnrgfquheppotiomrtqqazgryenprv5abio26

**Comment by Suyanj** [comment] 2023-11-13 02:46
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6qmjnybcqpivyhtef6prqcgog2ikflgub6l3gcxi6yzpmbimnc6 
#### Address 
> f1ynotqzocbg2mzsnhtie6ozkyzxtkkdj2n3ooily
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> ba54d45c-c604-4f29-acc0-682d2df76c1f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6qmjnybcqpivyhtef6prqcgog2ikflgub6l3gcxi6yzpmbimnc6

**Comment by herrehesse** [comment] 2023-11-13 12:39
![Screenshot 2023-11-13 at 13 38 35](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/45b4ea41-2ad8-4158-856f-26a5d165e917)

Ofcourse! FULL VPN fake location time again.

@kevzak Can you close this LDN?

**Comment by nora310** [comment] 2023-11-14 02:36
@herrehesse **Show your evidence.**

> ![Screenshot 2023-11-13 at 13 38 35](https://user-images.githubusercontent.com/70132857/282462496-45b4ea41-2ad8-4158-856f-26a5d165e917.png)
> 
> Ofcourse! FULL VPN fake location time again.
> 
> @kevzak Can you close this LDN?

**Comment by herrehesse** [comment] 2023-11-14 08:19
![Screenshot 2023-11-14 at 09 18 26](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/41b41e23-0b61-448d-9427-651948497b89)

Because you asked so kindly. This is the most abusive application I have seen all of this month.

@kevzak can we close this immediately before abusive notaries sign again?

**Comment by nora310** [comment] 2023-11-27 06:53
> ![Screenshot 2023-11-14 at 09 18 26](https://private-user-images.githubusercontent.com/70132857/282707500-41b41e23-0b61-448d-9427-651948497b89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjcyNzIsIm5iZiI6MTcwMTA2Njk3MiwicGF0aCI6Ii83MDEzMjg1Ny8yODI3MDc1MDAtNDFiNDFlMjMtMGI2MS00NDhkLTk0MjctNjUxOTQ4NDk3Yjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA2MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMmQyZDdhM2Q1YjIwMWVhOWYwODAzODQ3YzQxMTBkYjZmYmMxMTY0YmI0MzZhMzAzNjcyOGUxODI5ZmJhOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fk4uSy41hycRSqsWEiBoXjfFSc9vDcv-LUTYc1CAoVM)
> 
> Because you asked so kindly. This is the most abusive application I have seen all of this month.
> 
> @kevzak can we close this immediately before abusive notaries sign again?

Ridiculous

**Comment by kevzak** [comment] 2023-11-27 18:15
checker:manualTrigger

**Comment by Filplus-govteam** [comment] 2023-11-27 18:16
checker:manualTrigger

**Comment by Filplus-govteam** [comment] 2023-11-27 18:22
SPs provided

f02218611 | Dave | Dulles Town Center, Virginia, US | no | Dave
f01844118 | Garry | no email here | New York City, New York, US | no | garry
f01844232 | Lukas | iluka3312@gmail.com | individual | Dallas, Texas, US | no | Lukas
f01844043 | Abel | Abel | Ashburn, US | no | Abel
f01843994 | Hans | individual | Dulles Town Center, Virginia, US | no | hans6

Emailing SPs to confirm entity and location confirmation. No email for Garry in NYC. Closing this until SPs confirmed

**Closed by Filplus-govteam** 2023-11-27 18:22 UTC
Labels: verified client, granted
