### ISSUE TITLE
[DataCap Application]  ESRF

### ISSUE THREAD

**Issue by ssnks1** [filecoin-project/filecoin-plus-large-datasets#2108] opened 2023-07-20 10:35 UTC
### Data Owner Name

ESRF

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

France

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.esrf.fr/about

### Social Media

```text
https://www.esrf.fr/about
```

### Total amount of DataCap being requested

12PiB

### Expected size of single dataset (one copy)

10

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
With a brand-new generation of high-energy synchrotron, the ESRF is the world's brightest X-ray source and a centre of excellence for fundamental and innovation-driven research in condensed and living matter science. 

On August 2020, the ESRF opened its completely rebuilt x-ray source, ESRF-EBS (Extremely Brilliant Source), the world’s first fourth-generation high-energy synchrotron.

The ESRF - The European Synchrotron Radiation Facility - is the most intense source of synchrotron-generated light, producing X-rays 100 billion times brighter than the X-rays used in hospitals. These X-rays, endowed with exceptional properties, are produced at the ESRF by the high energy electrons that race around the storage ring, a circular tunnel measuring 844 metres in circumference.

The ESRF was conceived as a true European collaboration for the advancement of X-ray science. In 1988, eleven European countries joined forces to build the world’s most performing and bright « third-generation » light source. This visionary project has made an outstanding contribution to the excellence of European science. Almost thirty years later, a new dream saw the light, with the launch of a brand-new generation of high-energy synchrotron, the ESRF's Extremely Brilliant Source. With the support of ESRF's 21 partner countries, EBS provides scientists from all over the world with new opportunities to pioneer innovative science and to addressing the complex global challenges that our society faces.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The ESRF - The European Synchrotron Radiation Facility - is the most intense source of synchrotron-generated light, producing X-rays 100 billion times brighter than the X-rays used in hospitals. These X-rays, endowed with exceptional properties, are produced at the ESRF by the high energy electrons that race around the storage ring, a circular tunnel measuring 844 metres in circumference.
Each year, the demand to use these X-ray beams increases and near to 9000 scientists from around the world come to Grenoble, to “beamlines”, each equipped with state-of-the-art instrumentation, operating 24 hours a day, seven days a week.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
We counted the public data of this website, a total of 1.26P：
https://drive.google.com/file/d/1EhtvpNXieZCy6urozCeRKIuF0xO86dIK/view

This is the data usage agreement of the website, https://www.esrf.fr/datapolicy
What we count is public data, data that can be downloaded and stored.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment] 2023-07-20 10:48
The initial request for 12 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.

Advising notaries not to engage.

> 'We counted the public data of this website, a total of 1.26P：
> https://drive.google.com/drive/my-drive"

**Comment by Sunnyiscoming** [comment] 2023-07-20 15:21
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by Filplus-govteam** [comment] 2023-07-20 19:50
Hello @ssnks1 per the [new guidelines](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data. 

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by ssnks1** [comment] 2023-08-01 08:47
We are communicating with sp,  it will be confirmed within 3 days.

**Comment by Sunnyiscoming** [comment] 2023-08-05 14:24
Any update here?

**Comment by ssnks1** [comment] 2023-08-07 03:56
Hi, sorry for the late reply:
1. When you pass our application, SP can start.
2. I am a data preparer. We have been join in Filecoin for three years. We are proficient in using lotus, boost, singularity, and graphsplit.
3. We will be using singularity to prepare and package car files, we are ready.
4. Data is stored on the Filecoin network for the first time, which we believe is valuable.
5. We plan to cooperate with f02234424, f02252111, f02252024, f02252097, f02058333, f02252023, f01422327 and more SPs.

**Comment by ssnks1** [comment] 2023-08-09 06:45
Hi, we submitted now, thanks for the reminder
<img width="753" alt="WX20230809-144426@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/136078256/4ad23eca-9f2d-4e93-9dd5-3097bf42b7cf">

**Comment by ssnks1** [comment] 2023-08-10 05:03
@Sunnyiscoming @Filplus-govteam please help us，thanks

**Comment by Filplus-govteam** [comment] 2023-08-11 15:07
Confirming SP Entities received

f02252111 |  TopHub pool | Malaysia | 
f02105010 |  TopHub pool | Malaysia | 
f02252097 |  VieDvn | Vietnam | 
f02234424 |  algorith data | USA | 
f02058333 |  algorith data | USA | 

will reach out to confirm entity and location

**Comment by ssnks1** [comment] 2023-08-15 07:55
@Filplus-govteam Sorry, our plans have changed, we want to replace 2 nodes.

we want to put f02234424 and f02058333 replaced with f02036170 and f02036171

**Comment by ssnks1** [comment] 2023-08-15 08:11
f02252111 | TopHub pool | Malaysia |
f02105010 | TopHub pool | Malaysia |
f02252097 | VieDvn | Vietnam |
f02234424 | Ding Sheng Cloud | HK |
f02058333 | Ding Sheng Cloud | HK |

**Comment by ssnks1** [comment] 2023-08-15 08:11
Please confirm as soon as possible, thank you

**Comment by Filplus-govteam** [comment] 2023-08-15 22:00
ok thank you @ssnks1. FYI @Sunnyiscoming

**Comment by Sunnyiscoming** [comment] 2023-08-16 15:16
### Datacap Request Trigger
**Total DataCap requested**
> 12PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq

**Comment by stcouldlisa** [comment] 2023-08-18 07:53
First round, willing to support

**Comment by stcouldlisa** [comment] 2023-08-18 07:57
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiwr3gwhw4zfd3bkbq5u6odhn56hd6i2lzoig64wex6kkjf5ghk6 
#### Address 
> f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 7e1bfcce-96b5-4f52-9022-2c58faea3907
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiwr3gwhw4zfd3bkbq5u6odhn56hd6i2lzoig64wex6kkjf5ghk6

**Comment by NFTSTAR2023** [comment] 2023-08-18 10:32
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4aiyon5lkffif5leeuplakrowiuylb6fxc4a4cml6u24hjzpu3o 
#### Address 
> f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1c36q3bpodeddiers557j6e2mafw3oglitx56vty
#### Id
> 7e1bfcce-96b5-4f52-9022-2c58faea3907
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4aiyon5lkffif5leeuplakrowiuylb6fxc4a4cml6u24hjzpu3o

**Comment by NFTSTAR2023** [comment] 2023-08-18 10:36
I have done due diligence, there are no more question since now. 
I will keep my eye on this. 
This is my first time to sign for a client. actually i'd like to check whether my wallet is working.

**Comment by ssnks1** [comment] 2023-08-19 14:10
checker:manualTrigger

**Comment by junyaoren** [comment] 2023-08-20 02:48
checker:manualTrigger

**Comment by kernelogic** [comment] 2023-08-20 03:05
> https://drive.google.com/drive/my-drive
The URL for data sample points to "My drive" page. We cannot see it. Please share the folder to the public.

**Comment by ssnks1** [comment] 2023-08-20 03:28
https://drive.google.com/file/d/1EhtvpNXieZCy6urozCeRKIuF0xO86dIK/view

**Comment by ssnks1** [comment] 2023-08-20 03:34
Thank you for letting us know, the link has expired, we uploaded the link again, thank you

**Comment by ssnks1** [comment] 2023-08-20 05:33
checker:manualTrigger

**Comment by ssnks1** [comment] 2023-08-20 05:35
We are looking for the help of notary, can someone help us, thanks ！

**Comment by maxvint** [comment] 2023-08-20 08:18
checker:manualTrigger

**Comment by maxvint** [comment] 2023-08-20 09:15
Data distribution looks very good, and check all the boxes, retrieval also works very well, willing to support.

**Comment by maxvint** [comment] 2023-08-20 10:24
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5j4pttyjbyja5klqrtjskjw2rvvgozlwc256yul6k5jmhuv7jlg 
#### Address 
> f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 7e1bfcce-96b5-4f52-9022-2c58faea3907
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5j4pttyjbyja5klqrtjskjw2rvvgozlwc256yul6k5jmhuv7jlg

**Comment by nj-steve** [comment] 2023-08-20 12:34
checker:manualTrigger

**Comment by nj-steve** [comment] 2023-08-20 13:40
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/15796059/96b4b8ac-8bcb-424d-acae-158e67fcd322)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/15796059/f1799bcf-4933-4f65-adc1-84db5ccfcb0c)

**Comment by nj-steve** [comment] 2023-08-20 13:41
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearsaelzq5kvr7hoqxc6knwabpgug737css3pvwkzs2257rvu77ue 
#### Address 
> f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 7e1bfcce-96b5-4f52-9022-2c58faea3907
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearsaelzq5kvr7hoqxc6knwabpgug737css3pvwkzs2257rvu77ue

**Comment by nj-steve** [comment] 2023-08-20 13:42
also hope you to send deals to more SPs and more areas

**Comment by ssnks1** [comment] 2023-08-21 08:16
In the first round, 512T, the bot was normal.
In the second round, the DC was used up and the bot was not triggered, but it was still possible to sign #2108 at https://filplus.fil.org/#/, but only 512T.
We encountered this situation for the first time, we tried to find someone to sign, and then the 512T arrived.
Now, the second round of 512T is used up, the bot is not working, https://filplus.fil.org/#/ can already see #2108, only 512T.

Now, I hope you can help us to let the bot trigger 1P.

**Comment by junyaoren** [comment] 2023-08-21 08:43
checker:manualTrigger

**Comment by junyaoren** [comment] 2023-08-21 08:47
Overall statistics look good. Also tried manual retrieval, and the transmitting speed is decent. I will support this round.

**Comment by junyaoren** [comment] 2023-08-21 08:48
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceankbswqntdazkyqbllja72qqt32av2fy5evlcmudzcjosjxtr3u6 
#### Address 
> f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty
#### Id
> e645cf69-fe66-4e13-8d46-2ae227de2a48
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceankbswqntdazkyqbllja72qqt32av2fy5evlcmudzcjosjxtr3u6

**Comment by Aaron01230** [comment] 2023-08-21 09:26
The report shows that retrieval success rate is high and SP distribution is healthy and data replication is healthy, i will support this round.

**Comment by Aaron01230** [comment] 2023-08-21 09:28
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedicq6wzhhb7krhsm4zi54duuvvrylhgqzbofxnwkzgypmfx3wm7m 
#### Address 
> f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> e645cf69-fe66-4e13-8d46-2ae227de2a48
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedicq6wzhhb7krhsm4zi54duuvvrylhgqzbofxnwkzgypmfx3wm7m

**Comment by ssnks1** [comment] 2023-08-25 08:51
Sorry, maybe I didn't understand your idea, what do you need I to do?

**Comment by herrehesse** [comment] 2023-08-25 10:32
@ssnks1 we can not perform due diligence on your miners, so I do not understand why notaries have signed so far. Please upload one of your CID car files to [datasetcreators](http://send.datasetcreators.com/) for us to check and confirm.

**Comment by herrehesse** [comment] 2023-08-25 10:33
@Aaron01230 Why didnt you check the files before approving?

**Comment by ssnks1** [comment] 2023-08-27 14:33
checker:manualTrigger

**Comment by ssnks1** [comment] 2023-08-27 14:40
The bot is not triggering, it looks like the bot is not working anymore @jbesraa @kevzak @raghavrmadya @simonkim0515

**Comment by ssnks1** [comment] 2023-08-28 02:29
@jbesraa Thanks for your hard work, the bot has been fixed. @cryptowhizzard  https://send.datasetcreators.com/ can only upload 32G of data, so we  need to do some data processing, can you directly retrieve, download, and view it?

**Comment by Casey-PG** [comment] 2023-08-28 05:50
checker:manualTrigger

**Comment by Casey-PG** [comment] 2023-08-28 05:59
Need to increase the number of SP to make it more decentralized. Support this round and look forward to improvements.

**Comment by Casey-PG** [comment] 2023-08-28 06:04
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebox67xgb2md4toqeac7jivivytdvilqpscz2kj63r2cdkj76xgeu 
#### Address 
> f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 3efa9148-03f7-4f72-9fdc-9abd79e65845
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebox67xgb2md4toqeac7jivivytdvilqpscz2kj63r2cdkj76xgeu

**Comment by 1ane-1** [comment] 2023-08-28 06:34
Retrieveal is ok,but please pay attention to the deal data replication.Support  for this round

**Comment by 1ane-1** [comment] 2023-08-28 06:36
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrwk2q54dt3t542dypi6qiilq2fzkwkxbo27au3hrkwhp3mzftv4 
#### Address 
> f1acwgjze7ean4pzwtbik3dabzuqxlczztjfam3xq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 3efa9148-03f7-4f72-9fdc-9abd79e65845
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrwk2q54dt3t542dypi6qiilq2fzkwkxbo27au3hrkwhp3mzftv4

**Comment by kevzak** [comment] 2023-08-31 12:22
checker:manualTrigger

**Comment by kevzak** [comment] 2023-08-31 12:29
SPs provided:
f02252111 | TopHub pool | Malaysia |
f02105010 | TopHub pool | Malaysia |
f02252097 | VieDvn | Vietnam |
f02234424 | Ding Sheng Cloud | HK |
f02058333 | Ding Sheng Cloud | HK |

SPs taking deals:
f02238557 | New York City, New York, USCologix, Inc | 72.50 TiB | 2.90% | 72.50 TiB | 0.00%
**f02105010** | Kuala Lumpur, Kuala Lumpur, MYExtreme Broadband - Total Broadband Experience | 893.63 TiB | 35.73% | 893.63 TiB | 0.00%
**f02252111** | Kuala Lumpur, Kuala Lumpur, MYExtreme Broadband - Total Broadband Experience | 697.44 TiB | 27.89% | 697.44 TiB | 0.00%
f02036171 | Hong Kong, Central and Western, HKHGC Global Communications Limited | 70.44 TiB | 2.82% | 68.44 TiB | 2.84%
f02036170 | Hong Kong, Central and Western, HKHGC Global Communications Limited | 69.13 TiB | 2.76% | 67.25 TiB | 2.71%
**f02252097** | Hanoi, Hanoi, VNVNPT Corp | 697.69 TiB | 27.90% | 697.69 TiB | 0.00%

@ssnks1 80% of deals across 3 SP IDs , all under VPN likely the same location. 

distribution needs to be across 4 SP entities, also SP IDs you provided do not match. Closing this per 922 until you confirm your storage plan.

**Closed by kevzak** 2023-08-31 12:29 UTC
Labels: verified client, granted, very large application, data type: open public

**Comment by cryptowhizzard** [comment] 2023-09-02 15:38
Dear ssnks1,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqbute57rqdaw4qftoelbi2btegfeq4skf2bf6n7ijuqi7xtxmc4ly ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by ssnks1** [comment] 2023-12-01 02:14
> SPs provided: f02252111 | TopHub pool | Malaysia | f02105010 | TopHub pool | Malaysia | f02252097 | VieDvn | Vietnam | f02234424 | Ding Sheng Cloud | HK | f02058333 | Ding Sheng Cloud | HK |
> 
> SPs taking deals: f02238557 | New York City, New York, USCologix, Inc | 72.50 TiB | 2.90% | 72.50 TiB | 0.00% **f02105010** | Kuala Lumpur, Kuala Lumpur, MYExtreme Broadband - Total Broadband Experience | 893.63 TiB | 35.73% | 893.63 TiB | 0.00% **f02252111** | Kuala Lumpur, Kuala Lumpur, MYExtreme Broadband - Total Broadband Experience | 697.44 TiB | 27.89% | 697.44 TiB | 0.00% f02036171 | Hong Kong, Central and Western, HKHGC Global Communications Limited | 70.44 TiB | 2.82% | 68.44 TiB | 2.84% f02036170 | Hong Kong, Central and Western, HKHGC Global Communications Limited | 69.13 TiB | 2.76% | 67.25 TiB | 2.71% **f02252097** | Hanoi, Hanoi, VNVNPT Corp | 697.69 TiB | 27.90% | 697.69 TiB | 0.00%
> 
> @ssnks1 80% of deals across 3 SP IDs , all under VPN likely the same entity/location.
> 
> Your distribution needs to be distributed across 4 SP entities
> 
> Also the SP IDs you provided do not match who is storing deals.
> 
> Closing this per 922 until you confirm your storage plan and distribution.

Dear person in charge, @kevzak we have disclosed the SP we cooperate with and look forward to your help in reopening. Thank you for your help and patience. I wish you a good day, good health and a happy life.

**Comment by Filplus-govteam** [comment] 2023-12-01 14:04
@ssnks1 please resubmit registration form with SP contact information to confirm entity and location listed. https://www.jotform.com/231862753015656

**Comment by ssnks1** [comment] 2023-12-01 15:16
Hey,  @Filplus-govteam gm, thank you for your reply. We have filled out the form as per your request. We hope to get your help. 
<img width="743" alt="WX20231201-231459@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/136078256/c4f1503d-1b86-42d6-96e4-e423efcae24a">

**Comment by Filplus-govteam** [comment] 2023-12-01 17:13
SP list proivded
SP 1 | f02238557 | FAFOB | New York | no | shu
f02105010 |  TopHub pool | Malaysia | no | hantaowang
f02252111 |  TopHub pool | TMalaysia | no | hantaowang
f02036171 | doris | applecould | HK | no | doris
f02036170 | doris | applecould | HK | no | doris

emails sent to confirm

**Comment by Filplus-govteam** [comment] 2023-12-01 17:19
f02229545 | Los Angeles, California, USCNSERVERS LLC | 199.13 TiB | 4.86% | 199.13 TiB | 0.00%
**f02238557** | Leisure Village, New Jersey, USCologix, Inc | 72.50 TiB | 1.77% | 72.50 TiB | 0.00%
**f02252111** | Kuala Lumpur, Kuala Lumpur, MYExtreme Broadband - Total Broadband Experience | 972.81 TiB | 23.76% | 972.81 TiB | 0.00%
**f02105010** | Kuala Lumpur, Kuala Lumpur, MYExtreme Broadband - Total Broadband Experience | 898.50 TiB | 21.94% | 898.50 TiB | 0.00%
**f02036170** | Hong Kong, Central and Western, HKHGC Global Communications Limited | 90.06 TiB | 2.20% | 88.19 TiB | 2.08%
**f02036171** | Hong Kong, Central and Western, HKHGC Global Communications Limited | 90.06 TiB | 2.20% | 88.06 TiB | 2.22%
f02227496 | Hong Kong, Central and Western, HKIPTELECOM ASIA | 199.81 TiB | 4.88% | 199.81 TiB | 0.00%
f02229505 | Hong Kong, Central and Western, HKIPTELECOM Global | 199.94 TiB | 4.88% | 199.94 TiB | 0.00%
f02230309 | Putra Heights, Selangor, MYTechAvenue Malaysia | 200.00 TiB | 4.88% | 200.00 TiB | 0.00%
f02233568 | Paripark, Seoul, KRThe Constant Company, LLC | 199.00 TiB | 4.86% | 199.00 TiB | 0.00%
f02252097 | Hanoi, Hanoi, VNVNPT Corp | 972.94 TiB | 23.76% | 972.94 TiB | 0.00%

@ssnks1 who is f02252097 | Hanoi, Hanoi, VNVNPT Corp | storing 23.76% of deals? They were not mentioned above

**Comment by ssnks1** [comment] 2023-12-02 15:13
We have updated the cooperative SPs as required and hope to get your support and updates. @Filplus-govteam , Sincerely, thank you

**Comment by Filplus-govteam** [comment] 2023-12-04 13:57
No one has confirmed yet via email of a confirmation of who they are. 

Also, please provide contact info for
f02252097 | VieDvn | Vietnam

**Comment by ssnks1** [comment] 2024-01-04 02:55
fomi56192@gmail.com

**Comment by ssnks1** [comment] 2024-01-04 02:56
Sorry, I'm just getting back to you now.

The SP we have recently cooperated with contacted us and they need to start packaging.

Hope to see you reopen for us
