### ISSUE TITLE
Dcent - Help Ukrainian miners - Part 2

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#540] opened 2022-07-29 20:51 UTC
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dcent network
- Website / Social Media: www.dcent.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 different datasets with 20+ different miners.
```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have been contacted by miners from Ukraine to help them make a backup of their data in case anything happens given the situation in their country. The data will consists of sectors of the miners involved. The batch will be 500 TB we intend and we intend to spread it over 4 to 6 SP's.

This issue is a followup to issue #348. 

Set 1 contais 400 TB of sectors and cache data. We have packed it and uploaded it. In the mean time we received another 400 TiB of data for this LDN.

```
Where was the data in this dataset sourced from?
```
The miners uploaded it towards us.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, but we prefer to keep that private until uploaded for security reasons.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Just a few times for checking but we hope that it won't be necessary  offcourse.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / China / US / Australia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by kevzak** [comment] 2022-08-16 17:28
@raghavrmadya

**Comment by Sunnyiscoming** [comment] 2022-08-18 08:48
> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
> Yes, but we prefer to keep that private until uploaded for security reasons.

Hi, @cryptowhizzard  As you said, this dataset is more suitable for the private enterprise data request pattern.

As Deep mentioned filecoin-project/notary-governance#514, you will need to find notaries that can support your application since it includes private enterprise data.

You will need to follow a process similar to filecoin-project/notary-governance#489. This means:

Find notaries that can support your application. You can do this best in Slack, #fil-plus or #fil-plus-application-review
Once you have them, make an issue in the Notary Governance repo, similar to filecoin-project/notary-governance#489, stating your plan and the notaries that can support your request

**Comment by Sunnyiscoming** [comment] 2022-08-18 09:39
https://www.linkedin.com/dcent
This link can not be found.

**Comment by cryptowhizzard** [comment] 2022-08-18 09:57
> https://www.linkedin.com/dcent
> This link can not be found.

I will page Hidde for this

**Comment by cryptowhizzard** [comment] 2022-08-18 10:05
https://www.linkedin.com/company/dcent-b-v/

**Comment by raghavrmadya** [comment] 2022-08-18 21:41
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 300 TiB

**Client address**

> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a

**Comment by psh0691** [comment] 2022-08-26 05:32
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsti53tip3aj6hyehffxdlw5vti3z4jqngxyfpvdxnfykdypd2cg 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsti53tip3aj6hyehffxdlw5vti3z4jqngxyfpvdxnfykdypd2cg

**Comment by dannyob** [comment] 2022-08-30 20:12
Hey @cryptowhizzard , I'm willing to consider this for approval (at least until we get the Enterprise program up and running). Would you be prepared to share details with me of the clients and the anticipated data?

**Comment by cryptowhizzard** [comment] 2022-08-30 20:19
Yes , please contact me on slack for this.

**Comment by s0nik42** [comment] 2022-08-31 07:55
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasqlaf3dbiywtisywi3nezth6sw6i3fr44y23mgaedrtlrgi6t4u 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasqlaf3dbiywtisywi3nezth6sw6i3fr44y23mgaedrtlrgi6t4u

**Comment by Reiers** [comment] 2022-11-04 12:41
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlyszuasi4o3jokvry4tiytypt2huqjxo4ositbi3oh37ojtmvj4 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlyszuasi4o3jokvry4tiytypt2huqjxo4ositbi3oh37ojtmvj4

**Comment by kernelogic** [comment] 2022-11-04 15:43
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecz3ujfpyfm5oqw55xpppbjnuis7zjqqgav47ructu2d2zlkr45ac 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecz3ujfpyfm5oqw55xpppbjnuis7zjqqgav47ructu2d2zlkr45ac

**Comment by kernelogic** [comment] 2022-11-12 18:24
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec43ci5n5u6bbsauancevwxorbdrvq3a5ef7uc4hjnvjazqwhzmiw 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 08798a40-b9d1-40f0-9102-07bf2e20e67c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec43ci5n5u6bbsauancevwxorbdrvq3a5ef7uc4hjnvjazqwhzmiw

**Comment by liyunzhi-666** [comment] 2022-11-13 14:19
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedidzycmyxlgqj3dyi2g4pfhxb3iowmd5bh6zmxybkx6e2ynbqqiw 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 08798a40-b9d1-40f0-9102-07bf2e20e67c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedidzycmyxlgqj3dyi2g4pfhxb3iowmd5bh6zmxybkx6e2ynbqqiw

**Comment by mjroddy** [comment] 2022-11-21 04:56
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafy7hpgrumcylonjndoni5x7bcujszpnvxey4cngyufarbxyhbow 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 23cd768e-7ca0-4ba0-b50b-c26a0940a7c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafy7hpgrumcylonjndoni5x7bcujszpnvxey4cngyufarbxyhbow

**Comment by cryptowhizzard** [comment] 2022-11-22 13:24
Hello,
 
 
This was approved while the faucet was empty. Can someone reset it so we can get the tranche of 1.17 PB approved?

**Comment by raghavrmadya** [comment] 2022-11-22 16:06
## DataCap Allocation requested

### Request number 4
#### Multisig Notary address
> f01858410

#### Client address
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a

#### DataCap allocation requested
> 1.17PiB

**Comment by raghavrmadya** [comment] 2022-11-22 16:08
Checked and confirmed the error recognized by the client did happen. Retriggering request #4 manually. @mjroddy @xinaxu , please sign again if you still support

**Comment by xinaxu** [comment] 2022-11-22 16:55
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblnu3zo2xiipfuctr5t7d7kfxxb4ybqlevzt6mqws6szikoy4hei 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblnu3zo2xiipfuctr5t7d7kfxxb4ybqlevzt6mqws6szikoy4hei

**Comment by mjroddy** [comment] 2022-11-22 21:26
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6kmbpyb5ifbcdly4qppwrrjow5mwgdkrwrjgqysovolf5luj75s 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6kmbpyb5ifbcdly4qppwrrjow5mwgdkrwrjgqysovolf5luj75s

**Comment by mjroddy** [comment] 2022-11-24 07:31
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedb2u43vcdfmysfh5fql56g7cwtz6o6sxnqbqbgzod4ptoyfnycfu 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 989ad6c3-e1be-40bb-b021-66ee31df599e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb2u43vcdfmysfh5fql56g7cwtz6o6sxnqbqbgzod4ptoyfnycfu

**Comment by cryptowhizzard** [comment] 2022-11-24 10:53
@raghavrmadya 

Can you please recheck this? 

Seems the datacap still was not applied.

**Comment by kernelogic** [comment] 2022-11-24 15:36
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedro4yfggqynlazznr6c2s6zxq2eeqrikz65aqqwqzasstbscv7vg 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 989ad6c3-e1be-40bb-b021-66ee31df599e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedro4yfggqynlazznr6c2s6zxq2eeqrikz65aqqwqzasstbscv7vg

**Comment by filplus-checker** [comment] 2022-12-15 09:44
## DataCap and CID Checker Report[^1]
 - Organization: `Dcent network`
 - Client: `f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01886710](https://filfox.info/en/address/f01886710) has unknown IP location.

⚠️ [f01923553](https://filfox.info/en/address/f01923553) has unknown IP location.

⚠️ [f01848694](https://filfox.info/en/address/f01848694) has unknown IP location.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01928520](https://filfox.info/en/address/f01928520)       |         Maywood Park, Oregon, US |         715.13 TiB |     12.76% |  715.13 TiB |           0.00% |
| [f01882184](https://filfox.info/en/address/f01882184)       |         Singapore, Singapore, SG |         543.26 TiB |      9.69% |  543.26 TiB |           0.00% |
| [f01886710](https://filfox.info/en/address/f01886710)       |                          Unknown |         493.90 TiB |      8.81% |  468.30 TiB |           5.18% |
| [f01345523](https://filfox.info/en/address/f01345523)       |          Antwerpen, Flanders, BE |         381.28 TiB |      6.80% |  381.25 TiB |           0.01% |
| [f01392893](https://filfox.info/en/address/f01392893)       |     Amsterdam, North Holland, NL |         375.23 TiB |      6.70% |  374.25 TiB |           0.26% |
| [f01385207](https://filfox.info/en/address/f01385207)       |            Lincoln, Nebraska, US |         357.92 TiB |      6.39% |  357.23 TiB |           0.19% |
| [f01877571](https://filfox.info/en/address/f01877571)       |         Singapore, Singapore, SG |         343.21 TiB |      6.12% |  343.21 TiB |           0.00% |
| [f01953985](https://filfox.info/en/address/f01953985)`new`  |          Shenzhen, Guangdong, CN |         304.68 TiB |      5.44% |  304.40 TiB |           0.09% |
| [f01652333](https://filfox.info/en/address/f01652333)       |        Sunnyvale, California, US |         215.93 TiB |      3.85% |  201.04 TiB |           6.90% |
| [f01880047](https://filfox.info/en/address/f01880047)       |         Singapore, Singapore, SG |         192.55 TiB |      3.44% |  192.55 TiB |           0.00% |
| [f01915033](https://filfox.info/en/address/f01915033)       |             Chengdu, Sichuan, CN |         178.22 TiB |      3.18% |  177.94 TiB |           0.16% |
| [f022352](https://filfox.info/en/address/f022352)           |                   Oslo, Oslo, NO |         165.48 TiB |      2.95% |  165.04 TiB |           0.26% |
| [f01923553](https://filfox.info/en/address/f01923553)`new`  |                          Unknown |         150.03 TiB |      2.68% |  150.00 TiB |           0.02% |
| [f0117434](https://filfox.info/en/address/f0117434)`new`    |             Chengdu, Sichuan, CN |         134.07 TiB |      2.39% |  133.94 TiB |           0.10% |
| [f01208803](https://filfox.info/en/address/f01208803)       |      Sydney, New South Wales, AU |         133.80 TiB |      2.39% |  122.01 TiB |           8.82% |
| [f01929568](https://filfox.info/en/address/f01929568)`new`  |         Stockholm, Stockholm, SE |         129.50 TiB |      2.31% |  129.47 TiB |           0.02% |
| [f01208189](https://filfox.info/en/address/f01208189)       |      Sydney, New South Wales, AU |         102.87 TiB |      1.84% |  102.44 TiB |           0.41% |
| [f01829137](https://filfox.info/en/address/f01829137)       |             New Albany, Ohio, US |          96.65 TiB |      1.72% |   96.65 TiB |           0.00% |
| [f01208154](https://filfox.info/en/address/f01208154)       |      Sydney, New South Wales, AU |          87.68 TiB |      1.56% |   72.47 TiB |          17.35% |
| [f01886704](https://filfox.info/en/address/f01886704)       |            Las Vegas, Nevada, US |          79.07 TiB |      1.41% |   79.07 TiB |           0.00% |
| [f01886690](https://filfox.info/en/address/f01886690)       |            Las Vegas, Nevada, US |          74.67 TiB |      1.33% |   74.67 TiB |           0.00% |
| [f01208632](https://filfox.info/en/address/f01208632)       |      Sydney, New South Wales, AU |          53.04 TiB |      0.95% |   52.44 TiB |           1.15% |
| [f01882569](https://filfox.info/en/address/f01882569)       |             Atlanta, Georgia, US |          52.83 TiB |      0.94% |   52.82 TiB |           0.01% |
| [f01157271](https://filfox.info/en/address/f01157271)       |      Sydney, New South Wales, AU |          32.76 TiB |      0.58% |   32.29 TiB |           1.43% |
| [f01732189](https://filfox.info/en/address/f01732189)       |        San Diego, California, US |          25.40 TiB |      0.45% |   25.15 TiB |           0.98% |
| [f01206408](https://filfox.info/en/address/f01206408)       |      Sydney, New South Wales, AU |          23.32 TiB |      0.42% |   23.29 TiB |           0.13% |
| [f01157249](https://filfox.info/en/address/f01157249)       |      Sydney, New South Wales, AU |          21.22 TiB |      0.38% |   21.22 TiB |           0.00% |
| [f01157027](https://filfox.info/en/address/f01157027)       |      Sydney, New South Wales, AU |          21.06 TiB |      0.38% |   21.03 TiB |           0.15% |
| [f01156975](https://filfox.info/en/address/f01156975)       |      Sydney, New South Wales, AU |          20.11 TiB |      0.36% |   18.05 TiB |          10.25% |
| [f01157018](https://filfox.info/en/address/f01157018)       |      Sydney, New South Wales, AU |          19.94 TiB |      0.36% |   19.79 TiB |           0.74% |
| [f01848694](https://filfox.info/en/address/f01848694)       |                          Unknown |          17.93 TiB |      0.32% |   17.93 TiB |           0.00% |
| [f01156901](https://filfox.info/en/address/f01156901)       |      Sydney, New South Wales, AU |          16.39 TiB |      0.29% |   16.33 TiB |           0.33% |
| [f01207874](https://filfox.info/en/address/f01207874)       |      Sydney, New South Wales, AU |          11.38 TiB |      0.20% |   11.35 TiB |           0.27% |
| [f01207954](https://filfox.info/en/address/f01207954)       |      Sydney, New South Wales, AU |          10.45 TiB |      0.19% |   10.45 TiB |           0.04% |
| [f01208042](https://filfox.info/en/address/f01208042)       |      Sydney, New South Wales, AU |           8.73 TiB |      0.16% |    8.66 TiB |           0.76% |
| [f01127678](https://filfox.info/en/address/f01127678)       |       Łódź, Łódź Voivodeship, PL |           8.54 TiB |      0.15% |    8.54 TiB |           0.00% |
| [f01889910](https://filfox.info/en/address/f01889910)       |             Phoenix, Arizona, US |           4.12 TiB |      0.07% |    4.12 TiB |           0.00% |
| [f01154023](https://filfox.info/en/address/f01154023)       |      Sydney, New South Wales, AU |         960.51 GiB |      0.02% |  960.51 GiB |           0.00% |
| [f01156538](https://filfox.info/en/address/f01156538)       |      Sydney, New South Wales, AU |         256.00 GiB |      0.00% |  256.00 GiB |           0.00% |
| [f01199430](https://filfox.info/en/address/f01199430)       | Heerhugowaard, North Holland, NL |          96.00 GiB |      0.00% |   96.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/540/1671097470983.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 26.21% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         9.88 TiB |         9.88 TiB |                   1 |           0.18% |
|       164.79 TiB |       330.15 TiB |                   2 |           5.89% |
|       371.30 TiB |         1.10 PiB |                   3 |          20.14% |
|       193.00 TiB |       789.50 TiB |                   4 |          14.09% |
|        65.09 TiB |       326.89 TiB |                   5 |           5.83% |
|        56.25 TiB |       340.02 TiB |                   6 |           6.07% |
|        65.27 TiB |       463.82 TiB |                   7 |           8.28% |
|        75.79 TiB |       622.53 TiB |                   8 |          11.11% |
|        63.03 TiB |       575.54 TiB |                   9 |          10.27% |
|        45.09 TiB |       456.63 TiB |                  10 |           8.15% |
|        32.56 TiB |       358.69 TiB |                  11 |           6.40% |
|        10.84 TiB |       130.18 TiB |                  12 |           2.32% |
|         3.97 TiB |        51.79 TiB |                  13 |           0.92% |
|         1.39 TiB |        19.57 TiB |                  14 |           0.35% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/540/1671097471764.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi](https://filfox.info/en/address/f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/339) |           752.00 TiB |      18,148 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by herrehesse** [comment] 2023-02-10 07:46
checker:manualTrigger

**Comment by kernelogic** [comment] 2023-02-10 08:10
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecozahbh2omh4sfkvvoiyics5ojpnaghgdca3vjlk5kdkm4jde2wi 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 475.76TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> bf95490f-b431-4678-83ab-670933da0ca4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecozahbh2omh4sfkvvoiyics5ojpnaghgdca3vjlk5kdkm4jde2wi

**Comment by stcouldlisa** [comment] 2023-02-10 08:17
Contacted 50 SPs, I am like to support

**Comment by flyworker** [comment] 2023-02-10 08:56
CID Checker pass and can you provide a command for retrieval?

**Comment by lvschouwen** [comment] 2023-02-10 09:09
@flyworker 
Let me write a short tutorial on how to retrieve verified data.
We start with going to https://filplus.d.interplanetary.one/ and search the client, in this case we are looking for f01837713 - https://filplus.d.interplanetary.one/clients/f01837713

Once the page is done loading we can click on Export to CSV.
You can then search for the Miner ID or any random deal you would like to retrieve, we need to "Verified Deal ID".

The command to use is; lotus state get-deal 1234 (where 1234 is the Verified Deal ID)

This will result in a output with the PieceCID, Provider (this is also in the CSV) and the Label. Its the label we need for the retrieval.

The command to use is; lotus client retrieval --provider f01234 $Label $PieceCID

This will try and retrieve the file from the miner.

I hope this helps.

**Comment by psh0691** [comment] 2023-02-10 09:53
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwszs3vex6v7plw46vw63vhdsx67afn7azeelolo2ufi6qqbexb2 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 475.76TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> bf95490f-b431-4678-83ab-670933da0ca4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwszs3vex6v7plw46vw63vhdsx67afn7azeelolo2ufi6qqbexb2

**Comment by flyworker** [comment] 2023-02-10 10:29
> @flyworker Let me write a short tutorial on how to retrieve verified data. We start with going to https://filplus.d.interplanetary.one/ and search the client, in this case we are looking for f01837713 - https://filplus.d.interplanetary.one/clients/f01837713
> 
> Once the page is done loading we can click on Export to CSV. You can then search for the Miner ID or any random deal you would like to retrieve, we need to "Verified Deal ID".
> 
> The command to use is; lotus state get-deal 1234 (where 1234 is the Verified Deal ID)
> 
> This will result in a output with the PieceCID, Provider (this is also in the CSV) and the Label. Its the label we need for the retrieval.
> 
> The command to use is; lotus client retrieval --provider f01234 $Label $PieceCID
> 
> This will try and retrieve the file from the miner.
> 
> I hope this helps.

thanks for your information, learning new things everyday!

**Comment by jamerduhgamer** [comment] 2023-02-22 00:40
Is there something wrong with the datacap allocation for this LDN? According to the bot, it went over the 5 PiB total by ~2.21 PiBs? @simonkim0515 @raghavrmadya @panges2

**Comment by flyworker** [comment] 2023-02-22 01:06
@jamerduhgamer  they are using the same address with https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/348  that's why it pass 5PB

**Comment by jamerduhgamer** [comment] 2023-02-22 01:37
Ah that makes sense. It is causing a slight problem since the next tranche of datacap won't kick off then.

**Comment by Yvette516** [comment] 2023-05-25 08:56
checker:manualTrigger

**Closed** 2023-07-06 12:59 UTC
Labels: total datacap reached, validated, verified client, granted
