### ISSUE TITLE
[DataCap Application] <Shanghai Zhongyun Culture Media Co., Ltd.>

### ISSUE THREAD

**Issue by cici00000** [filecoin-project/filecoin-plus-large-datasets#1476] opened 2022-12-20 10:22 UTC
### Data Owner Name

Shanghai Zhongyun Culture Media Co., Ltd

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.hjfcn.com/

### Social Media

```text
http://www.hjfcn.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Zhongyun media team comes from top creative talents at home and abroad
Average working experience more than 8 years
Both film and television planning, senior director, photography director, art director
Lighting director, visual effects director, 3D director, post-production, etc.
Whole-chain personnel covering production and creation
Won the praise of countless customers
we will never be satisfied with the status quo
Constantly surpass ourselves, achieve customers and achieve team value!
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Corporate video、Product promotional video、Brand film/TVC、MG animation、3D CG animation、short video etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/YUoad6fPjYN
https://www.aliyundrive.com/s/ndCLng8Ah1c
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment] 2022-12-20 20:53
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia

**Comment by herrehesse** [comment] 2023-01-04 16:33
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment] 2023-02-13 13:26
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment] 2023-02-16 19:46
At current we don't charge it. It's only there in case someone submits dozens of requests.

**Comment by cryptowhizzard** [comment] 2023-02-20 12:31
Hi @cici00000 

Thanks!

I see you have not provided any SP's so i can't make an onboarding plan with your. Let me know when you are ready to provide the SP's so i can move on.

**Comment by stcouldlisa** [comment] 2023-02-27 06:21
It seems that there are more weekly applications for 400T

**Comment by a1991car** [comment] 2023-03-29 10:33
Please list 5 cooperative SPs, these SPs are distributed in 3 different continents, thank you.

**Comment by maxvint** [comment] 2023-04-03 04:05
@cici00000 Hello, can you give me more information about the SP's you finally confirmed? Their business name, region and city?

**Comment by maxvint** [comment] 2023-04-03 07:56
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxlttuzm5inhp2lqcy67rjfpkyytgo6tespifpm6kyyot672mgqi 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxlttuzm5inhp2lqcy67rjfpkyytgo6tespifpm6kyyot672mgqi

**Comment by simonkim0515** [comment] 2023-04-20 14:38
## DataCap Allocation requested

  ### Request number 2
  #### Multisig Notary address
> f02049625

  #### Client address
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia

  #### DataCap allocation requested
> 200TiB

  #### Id
> c9053d07-2712-41b2-8a96-af717f4c4e6c

**Comment by liyunzhi-666** [comment] 2023-04-21 08:07
checker:manualTrigger

**Comment by ipollo00** [comment] 2023-04-21 09:23
Hi, I have checked that those Sps are reachable.  Are you still using those SPs for the first round? 
Also, May I know if there is any problem or bug on your ticket's checker report? You should deal with it. @cici00000 

> Thank you for your question, the list of SPs is as follows, most of them are communicated by team members in various communities and do not have brand names, but can provide cities and regions:
> 
> SP Address	Region	City
> f01927554	CN	Shenzhen
> f01927252	England	Hounslow
> f01928022	US	Los Angeles
> f01932183	US	Los Angeles
> f02036170	CN	Hong Kong

**Comment by ipollo00** [comment] 2023-04-21 10:40
@cici00000 Thanks for the reply, I will support this round first, and wait for the governance team to fix it and follow up

**Comment by ipollo00** [comment] 2023-04-21 10:43
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec43ovwzzxmwj4ch3i5hogx47secgxb7jmzksn47yur43muliuefy 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec43ovwzzxmwj4ch3i5hogx47secgxb7jmzksn47yur43muliuefy

**Comment by stcouldlisa** [comment] 2023-04-24 04:37
checker:manualTrigger

**Comment by stcouldlisa** [comment] 2023-04-24 06:13
![WechatIMG554](https://user-images.githubusercontent.com/112812896/233913621-a0446b7c-2ee2-459c-8797-c414e56510e5.jpeg)

**Comment by stcouldlisa** [comment] 2023-04-24 06:19
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechilfdpaqjdqbf6zipehb64surimvxmog2aw43crycl2c4p3sqmw 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechilfdpaqjdqbf6zipehb64surimvxmog2aw43crycl2c4p3sqmw

**Comment by woshidama323** [comment] 2023-05-18 06:30
checker:manualTrigger

**Comment by NewHuoPool** [comment] 2023-05-18 06:49
checker:manualTrigger

**Comment by woshidama323** [comment] 2023-05-18 06:49
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkxk5wkjqotafpowm647pzrf6wnl4ssgtboh7ofr7rbhebziopti 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> aa486d00-1283-4a56-bff0-0d5dd49e762a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkxk5wkjqotafpowm647pzrf6wnl4ssgtboh7ofr7rbhebziopti

**Comment by NewHuoPool** [comment] 2023-05-18 07:33
![74283753cf80562a812180b6a9914ad](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/117884185/780ba22e-6fdc-4e23-b548-2225059614df)
The retrieval result is OK, willing to support this round.

**Comment by NewHuoPool** [comment] 2023-05-18 07:48
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbdj2l2plgkecrcuqe6phvabis3xe2k5fgy4opoleszy4vkvip5q 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f16karfxq7lxdy7izqrzrk75jf3not34k6sg6zvcy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbdj2l2plgkecrcuqe6phvabis3xe2k5fgy4opoleszy4vkvip5q

**Comment by Joss-Hua** [comment] 2023-05-18 09:33
look nice

**Comment by Joss-Hua** [comment] 2023-05-18 09:34
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrvs5foffpr4pdkd7gh64yhmlejndtdyr73zxc6l77ug7eatpy4i 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrvs5foffpr4pdkd7gh64yhmlejndtdyr73zxc6l77ug7eatpy4i

**Comment by sxxfuture-official** [comment] 2023-06-16 02:23
checker:manualTrigger

**Comment by sxxfuture-official** [comment] 2023-06-16 02:32
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxqwm2xeex7l3uqm75wz2v4iue443cbgcmre3v7lsozqukg3rkwu 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 533f9ac0-b63b-4a5f-a1b1-e632673176bc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxqwm2xeex7l3uqm75wz2v4iue443cbgcmre3v7lsozqukg3rkwu

**Comment by newwebgroup** [comment] 2023-06-16 04:03
The success rate of the search looks OK
> Retrieval Statistics
> Overall Graphsync retrieval success rate: 42.86%
> Overall HTTP retrieval success rate: 0.00%
> Overall Bitswap retrieval success rate: 0.00%

Need to pay attention to the dispersion of replicas
> Deal Data Replication
> ⚠️ 57.57% of deals are for data replicated across less than 4 storage providers.

**Comment by newwebgroup** [comment] 2023-06-16 04:04
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5lq2oi3k7bs32onlydc4ec3j44zodmmiwb3ai56chvj5wesq3p6 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 533f9ac0-b63b-4a5f-a1b1-e632673176bc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5lq2oi3k7bs32onlydc4ec3j44zodmmiwb3ai56chvj5wesq3p6

**Comment by newwebgroup** [comment] 2023-06-16 04:06
It looks like there are some bugs that cause Proposed to appear twice at the same time

**Comment by zcfil** [comment] 2023-06-16 05:51
checker:manualTrigger

**Comment by zcfil** [comment] 2023-06-16 05:54
⚠️ 57.57% of deals are for data replicated across less than 4 storage providers.
May I ask how your next round of data is planned, and are there any more SPs that can be allocated?

**Comment by zcfil** [comment] 2023-06-16 06:17
![66c2a9c138e5c80dea65084f6432a15](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/88f6f1bd-40c7-4880-a53d-61f06b9d51b0)
The retrieval is normal, and I hope to improve this issue as soon as possible. I support this round, but I will follow up on the data situation in the future.

**Comment by zcfil** [comment] 2023-06-16 06:24
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkn6z7v6dqh66wqwtr6dumnpshq6pudhlr2d4x7yjawnwvoua2l2 
#### Address 
> f172zurpjgt6a7kgjoka5q3e375zakyihqw5uhdia
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 533f9ac0-b63b-4a5f-a1b1-e632673176bc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkn6z7v6dqh66wqwtr6dumnpshq6pudhlr2d4x7yjawnwvoua2l2

**Comment by zcfil** [comment] 2023-06-27 06:19
checker:manualTrigger

**Comment by cryptowhizzard** [comment] 2023-07-28 12:40
Seems not all your SP's are online. Can you check that please?

cat 1476-f02100442-f01261113-36458604-baga6ea4seaqo47thfwbcu54bxzv4nzzfswo2jksds3i23vul5bgn2ageru65mhy.log
2023-07-26T20:34:52.831+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b:\\n  * [/ip4/183.2.199.100/tcp/24001] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b, but remote key matches 12D3KooWGz1oQXUbdLkVvBx1JoJSniCEiBQcZHH5HAQkA73Gm98W\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01261113\",\"MinerPeer\":{\"Address\":\"f01261113\",\"ID\":\"12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b\",\"PieceCID\":null}}"}
2023-07-26T20:34:52.831+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T20:37:30.903+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b:\\n  * [/ip4/183.2.199.100/tcp/24001] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b, but remote key matches 12D3KooWGz1oQXUbdLkVvBx1JoJSniCEiBQcZHH5HAQkA73Gm98W\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01261113\",\"MinerPeer\":{\"Address\":\"f01261113\",\"ID\":\"12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b\",\"PieceCID\":null}}"}
2023-07-26T20:37:30.903+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T20:39:52.034+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b:\\n  * [/ip4/183.2.199.100/tcp/24001] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b, but remote key matches 12D3KooWGz1oQXUbdLkVvBx1JoJSniCEiBQcZHH5HAQkA73Gm98W\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01261113\",\"MinerPeer\":{\"Address\":\"f01261113\",\"ID\":\"12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b\",\"PieceCID\":null}}"}
2023-07-26T20:39:52.034+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T20:42:26.760+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b:\\n  * [/ip4/183.2.199.100/tcp/24001] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b, but remote key matches 12D3KooWGz1oQXUbdLkVvBx1JoJSniCEiBQcZHH5HAQkA73Gm98W\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01261113\",\"MinerPeer\":{\"Address\":\"f01261113\",\"ID\":\"12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b\",\"PieceCID\":null}}"}
2023-07-26T20:42:26.760+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T20:44:19.610+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b:\\n  * [/ip4/183.2.199.100/tcp/24001] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b, but remote key matches 12D3KooWGz1oQXUbdLkVvBx1JoJSniCEiBQcZHH5HAQkA73Gm98W\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01261113\",\"MinerPeer\":{\"Address\":\"f01261113\",\"ID\":\"12D3KooWSS2R7ABXxvHmJuU1nfNhpD5ZLho79NZhkuX5QCUvwg8b\",\"PieceCID\":null}}"}
2023-07-26T20:44:19.610+0200	ERROR	retry	retry/retry.go:29	Failed after 5 attempts, last error: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
ERROR: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'

![Scherm­afbeelding 2023-07-28 om 14 39 53](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/fb0049bd-f857-4586-bdb5-72cc46b28431)

**Comment by cryptowhizzard** [comment] 2023-08-09 05:11
Good morning,

I managed to download some of your data and made it available through the link here:

http://datasetcreators.com/downloadedcarfiles/1476-f02100442-f01969746-49584005-baga6ea4seaqcygmsfnz5e2t3wuazfohmdnigbshopsxkxr5mo44sap757cl4gdi/

You stated that you would store :
Corporate video、Product promotional video、Brand film/TVC、MG animation、3D CG animation、short video etc.

However i don't see that here. Please explain?

**Comment by cryptowhizzard** [comment] 2023-09-02 15:30
Hello,

I have been downloading your data and made it available here:

http://www.datasetcreators.com/downloadedcarfiles/downloadedcarfiles/1476-f02100442-f01969746-49584005-baga6ea4seaqcygmsfnz5e2t3wuazfohmdnigbshopsxkxr5mo44sap757cl4gdi

This data does not match the data you indicated you were going to store?

**Comment by Sunnyiscoming** [comment] 2023-10-28 13:27
Hello, @cici00000 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by herrehesse** [comment] 2023-11-14 09:41
also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Filplus-govteam** [comment] 2023-11-22 17:56
SP list provided:

f01927252 | S&C | England | no | no
f01932183 | TK | US | no | no
f02274508 | H&W | HK | no | no
f02127382 | IndeCom | AU | no | no
f02145020 | Longcang | CN | no | no

**Comment by Filplus-govteam** [comment] 2023-11-22 17:56
checker:manualTrigger

**Comment by Filplus-govteam** [comment] 2023-11-22 17:59
SPs taking deals:
f01738789 | Osaka, Ōsaka, JPARTERIA Networks Corporation | 60.59 TiB | 2.73% | 60.59 TiB | 0.00%
f0130556 | Guangzhou, Guangdong, CNChina Mobile communications corporation | 58.31 TiB | 2.63% | 58.31 TiB | 0.00%
f01969746 | Beijing, Beijing, CNChina Unicom Beijing Province Network | 405.28 TiB | 18.25% | 405.22 TiB | 0.02%
f02226869 | Nanchang, Jiangxi, CNCHINA UNICOM China169 Backbone | 490.22 TiB | 22.08% | 490.22 TiB | 0.00%
f01261113new | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 313.97 TiB | 14.14% | 283.78 TiB | 9.61%
f02059207 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 127.75 TiB | 5.75% | 127.75 TiB | 0.00%
f01261218 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 8.31 TiB | 0.37% | 8.31 TiB | 0.00%
f02329561 | Hong Kong, Central and Western, HKDREAM POWER TECHNOLOGY LIMITED | 244.25 TiB | 11.00% | 244.25 TiB | 0.00%
f02121645new | Hanoi, Hanoi, VNDREAM POWER TECHNOLOGY LIMITED | 134.31 TiB | 6.05% | 134.31 TiB | 0.00%
f02051716 | Seattle, Washington, USGTHost | 26.50 TiB | 1.19% | 26.50 TiB | 0.00%
f02212982 | Santa Clara, California, USMajestic Hosting Solutions, LLC | 183.78 TiB | 8.28% | 183.78 TiB | 0.00%
f02235190new | Warsaw, Mazovia, PLOVH SAS | 166.91 TiB | 7.52% | 166.91 TiB | 0.00%

SP list does not match. Closing until a clear list of SP entities and distribution is provided

**Closed by Filplus-govteam** 2023-11-22 17:59 UTC
Labels: ready to sign, verified client
