### ISSUE TITLE
[DataCap Application] Filecoin Discover

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/filecoin-plus-large-datasets#1] opened 2021-05-17 19:36 UTC
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.
    
## Core Information

- Organization Name: Protocol Labs - Filecoin Discover
- Website / Social Media: store.filecoin-discover.com / protocol.ai 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- On-chain address for first allocation: f1g463yb4ok3lq3tffkvvfmfyngcagpx4kg7c7rei

## Project details

Share a brief history of your project and organization.
```
Protocol Labs is an open-source R&D lab. We build protocols, tools, and services to radically improve the internet. Our products serve thousands of organizations and millions of people. Protocols we’ve built to date include IPFS, Filecoin, libp2p, drand, IPLD and more. 

Our organization was founded back in 2014 - and you can find more detail about some of the important milestones along our history on our [website](https://protocol.ai/about/).  
```

What is the primary source of funding for this project?
```
Filecoin Discover is a project to store massive amounts of open source data on the Filecoin network. This has been funded by Protocol Labs (for the harvesting, processing, and preparation of data) - while participants in the program paid for shipping and hardware costs to transport the data to them. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
The primary stakeholders are Protocol Labs, as well as the community of miners who have committed capital to helping secure these open source datasets.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Each of these datasets come from reputable organizations - where the licensing allows for public storage of the data. The full list of datasets that are being stored can be found [here](https://store.filecoin-discover.com/pages/full-dataset-list).
```

Where was the data in this dataset sourced from?
```
These are open source datasets - either sourced from partners (like the Internet Archive) or the partners themselves on openly available site.
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Here are links to a few of the projects: 
- [Project Gutenburg](https://www.gutenberg.org/ebooks/)
- [USGS LandSat](https://earthexplorer.usgs.gov/)
- [OpenAQ](https://openaq.org/#/projects?page=1) - (Note these are transformed from the underlying raw data))

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
These are all public datasets that can be retrieved by anyone on the network. In some cases there may be local restrictions that apply, and where applicable we’ll be sharing the dataset licensing information on a web portal to distribute access to this data. 
```

What is the expected retrieval frequency for this data?
```
We expect that retrieval may be sporadic - some users may choose to retrieve this data to store their own archived copy, some may retrieve out of enjoyment - but it will really be dictated by public desire. We intend to run a retrieval bot to test retrieval of these datasets with the miners, to ensure the data is actually being served with fast retrieval - as will be specified in our deal making process. We’re still determining the exact parameters for this retrieval bot, but at a high level it will with regular consistency trigger retrieval requests from different addresses to verify if content is still being made available via fast-retrieval.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
We intend to store this for a minimum 12 months duration (up to 18 months at the miners discretion to increase the duration). We’re intending to enable renewals in the future, though this original application is simply for the onboarding of the initial datasets with a minimum redundancy of 5 copies per dataset. 
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
Given the scale of the dataset allocation, we set up a process for miners to specify what categories of data they were interested in storing, and on our side manually assigned subsections of the various datasets in order to get distribution. To ensure a diversity of miners, we put a cap on the number of drives any individual miner could purchase at 20 drives. 

As a result, per dataset we have a number of countries being represented - typically with each dataset being stored across ~3 continents at a minimum. 

```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We’ve invested a substantial amount of effort to enable miners to self-trigger the deals that they will be storing. To do this, we’ve architected a system whereby a miner with a valid drive and data can trigger a request to our Client node to make a deal. We’ve architected this in such a way that we’re able to manage processing many deals in parallel - to the point where we do not believe our Client node will be the rate limiting factor for onboarding. 

Given we have a diversity of miners participating in this program, we expect the onboarding process to take several months in total - though more powerful miners may onboard at a faster rate than smaller miners. We intend to impose a few forms of rate limiting to prevent abuse in our onboarding process. We anticipate using roughly 500TiB per week, though that may fluctuate depending on early factors. Our ideal scenario is that our total allocation is parceled out in 500TiB chunks, where we can onboard a batch of deals, show how the DataCap was allocated, and proceed. 

```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
Miners who were interested in participating were able to order hard drives and pay for shipping for their data. Miners were asked to run a registration script that validated the integrity of the data on the drives. When we begin the onboarding process, we’ll be using the offline deal mechanism to trigger the deals. 
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We allowed miners to self select into storing data for this program. Over a period of many weeks, we allowed miners to request up to 20 drives worth of data to be stored with them. To mitigate against over allocation (in the event a miner tried to acquire more than 20 drives), we’ve asked all participants to register their drives and data - which we also match against our internal manifest of shipments.

As we onboard drives, we intend to rate limit onboarding in the event a miner falls out of good standing with our client. This can happen for a number of reasons including:
- Our retrieval bot is unable to successfully retrieve content from miners (fast retrieval is a requirement for receiving deals) 
- We suspect a miner is onboarding more drives than the original limit of 20 drives (in which case a miner will have to reach out to us via Slack to remove the rate limit
- A miner is attempting to store data on a drive not supplied by the Discover program

```

How will you be distributing data and DataCap across miners storing data?
```
During our original sale period, we restricted miners to only purchase 20 drives for onboarding. Using the online store, we were able to get a distribution of miners who were able to store various datasets, and build a pipeline to allocate partial copies of the Discover datasets across the population of miners willing to store the relevant category. We’ve had hundreds of miners sign up to receive drives, but we recognize not all of them will onboard their capacity.

We intend to use DataCap commensurate with the data being stored by miners serving the Discover datasets with fast, free retrieval - so long as they meet our requirements for duration of storage (12 months minimum) and terms of storage. 

During the onboarding process, we’ll be easing in our onboarding to start - such that we have all miners able to attempt to onboard at roughly the same time. We recognize that the collateral requirements may be high for miners, so we do not set a minimum requirement for onboarding speed - allowing teams to onboard at their own rate. 

```

**Comment by KodaRobotDog** [comment] 2021-05-25 15:30
I would be the notary for this client.

**Comment by flyworker** [comment] 2021-05-29 22:27
@KodaRobotDog  Are you a notary already? I think you are still in the process of application to be a notary.

> I would be the notary for this client.

**Comment by steven004** [comment] 2021-06-11 07:24
Finally it comes 👍 . Congrats!
Does this require DataCaps granted by a notary from a corresponding area (e.g. Asia, NA) for the data storing in a specific area? 

In addition, I am very interested by the retrieving client, I would prefer an app to a website, since an app can be installed by users directly and it could really be distributed. If it is a website for retrieving, I would like to see an IPFS accessible website, thus, it can be decentralized too.

**Comment by MasaakiNawatani** [comment] 2021-06-11 08:46
@jnthnvctr @dkkapur Hi guys. I am willing to participate in this and be one of the Notaries to help out in LDC. Please let me know if there is anything else I need to do next. Thank you!

**Comment by s0nik42** [comment] 2021-06-11 14:30
I will support it too￼

**Comment by Fenbushi-Filecoin** [comment] 2021-06-11 15:22
We can help administer the case.

**Comment by neogeweb3** [comment] 2021-06-13 22:53
Count me in

**Comment by ozhtdong** [comment] 2021-06-19 11:05
I'm simon from 1475 team， +1

**Comment by swatchliu** [comment] 2021-06-19 13:38
Count me in +1

**Comment by andrewxhill** [comment] 2021-06-20 14:52
Textile is happy to support it!

**Comment by XnMatrixSV** [comment] 2021-06-21 02:54
we are willing to join this project.

**Comment by dkkapur** [comment] 2021-06-22 08:24
Looks like the project has support from 7 current notaries! Can each of you please confirm the following address for signing onto the multisig?

1. @steven004 - f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
2. @MasaakiNawatani - f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
3. @s0nik42 - f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
4. @Fenbushi-Filecoin - f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
5. @neogeweb3 - f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
6. @andrewxhill - f2kb4izxsxu2jyyslzwmv2sfbrgpld56efedgru5i
7. @XnMatrixSV - f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a

(@ozhtdong @KodaRobotDog @swatchliu - we need the current notary elections to wrap up fully before you are eligible for this. really appreciate your support and activity on this though!)

**Comment by steven004** [comment] 2021-06-22 09:30
thumbs up for yes!

**Comment by neogeweb3** [comment] 2021-06-22 15:17
Confirm.

**Comment by neogeweb3** [comment] 2021-06-22 15:18
Confirmed.

**Comment by andrewxhill** [comment] 2021-06-22 16:05
@dkkapur the orig address (not the multisig) is:`f1n4kuihubfesg55brkx5ntwqyglvbhydxjfodwra`

**Comment by MasaakiNawatani** [comment] 2021-06-23 01:51
@dkkapur that address is the one I used during the first round of Notary governance, since we needed a new address for round 2 of Notary elections, the correct one should be  - - - **f1nno2h7vh5h22kynap2ca7ywxwvxpbl2yclfbguq**

**Comment by Fenbushi-Filecoin** [comment] 2021-06-23 06:04
Confirmed

**Comment by XnMatrixSV** [comment] 2021-06-24 09:48
Confirmed.

**Comment by dkkapur** [comment] 2021-06-24 15:56
## Multisig Notary requested

#### Notary addresses
> f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
> f1nno2h7vh5h22kynap2ca7ywxwvxpbl2yclfbguq
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
> f1n4kuihubfesg55brkx5ntwqyglvbhydxjfodwra
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a

#### Total DataCap requested
> 5 PiB

#### Expected weekly DataCap usage rate
> 500 TiB

**Comment by ozhtdong** [comment] 2021-06-29 01:55
@dkkapur 
![image](https://user-images.githubusercontent.com/69976222/123725083-11ddc880-d8c0-11eb-957a-633983421c9a.png)
We are already notaries, please count me in，Thks！

**Comment by dkkapur** [comment] 2021-07-17 08:13
https://github.com/filecoin-project/notary-governance/issues/194 - this Notary is ready to begin providing DataCap to the client (represented by @jnthnvctr). Next steps are:
- we need to confirm the lead Notary. Based on the initial responses, I would like to request @steven004 or @MasaakiNawatani to see if they can serve as the lead on this one. Alternatively, any of the other 7 notaries can also be the lead! 
- @jnthnvctr whenever you are ready - please share a message here requesting your first DataCap allocation and the address to which you would like it received. The first DataCap request can be up to 250TiB for this application. 

Based on this, the lead notary will paste in the following message as a comment in this Issue: 

```
## DataCap Allocation requested
#### Multisig Notary address
> f01079326
#### Client address
> <addr2>
#### DataCap allocation requested
> <XTiB>
```

This will prompt the bot to show the request to the other Notaries on the multisig in the Fil+ Registry App. We need 4 Notaries to sign the request for it to go through.

**Comment by steven004** [comment] 2021-07-19 08:03
Sounds great!
@jnthnvctr , please let us know once this is ready to move on.

**Comment by jnthnvctr** [comment] 2021-07-19 13:07
Great - I think we're ready for the first allocation. We still have a few loose ends to tie up, but we're anticipating being able to start sometime this week if everything goes well. 

Please send 250TiB to this address! f1g463yb4ok3lq3tffkvvfmfyngcagpx4kg7c7rei

**Comment by dkkapur** [comment] 2021-07-19 16:31
Quick note - we ran into a bug with getting the request to show up correctly in the Fil+ app, based on an attempted allocation in #2; will update this Issue as well once we are ready to proceed.

**Comment by dkkapur** [comment] 2021-07-22 15:41
Hey folks - update today is that this should be good to go. There is still likely 1-2 minor front-end bugs but messages are posting to the chain from the Estuary issue correctly. @steven004 do you want to kick off sending the first request as per the instructions https://github.com/filecoin-project/filecoin-plus-large-datasets#granting-datacap-to-the-client?

**Comment by steven004** [comment] 2021-07-23 01:24
@jnthnvctr I have sent out the proposal of the first datacap for Filecoin Discover. 

**Message sent to Filecoin Network**
> [bafy2bzacebjykmz5htcxcb4m25goctpumokqbxia4dlxaokjcldro5q5fygfo](https://filscan.io/tipset/message-detail?cid=bafy2bzacebjykmz5htcxcb4m25goctpumokqbxia4dlxaokjcldro5q5fygfo)

**Address**
> [f1g463yb4ok3lq3tffkvvfmfyngcagpx4kg7c7rei](https://filscan.io/tipset/address-detail?address=f1g463yb4ok3lq3tffkvvfmfyngcagpx4kg7c7rei)

**Datacap Allocated**
> 250TiB

This  needs to be approved by at least other 3 notaries before it takes effect.

**Comment by dkkapur** [comment] 2021-07-26 16:12
Commenting with the formatted message here so it shows up in the app for other notaries:

## DataCap Allocation requested 
#### Multisig Notary address
> f01079326
#### Client address
> f1g463yb4ok3lq3tffkvvfmfyngcagpx4kg7c7rei
#### DataCap allocation requested
> 250TiB

**Comment by dkkapur** [comment] 2021-07-26 16:17
@andrewxhill @s0nik42 @neogeweb3, @XnMatrixSV, @MasaakiNawatani, @Fenbushi-Filecoin - this should be ready in the app for you. Signing in to sign it will require that you log into the app as an Organization, and use `f01079326` in the multisig address field. 

![image](https://user-images.githubusercontent.com/2343218/126524776-00f85687-e129-4b64-a5e2-ec88edb2e088.png)

**Comment by neogeweb3** [comment] 2021-07-26 18:07
signed

**Comment by dkkapur** [comment] 2021-07-29 09:52
@andrewxhill @s0nik42 @XnMatrixSV @MasaakiNawatani @Fenbushi-Filecoin - if you are good to support this first allocation of DataCap, can you please Approve the request via the app as per the instructions above? Thank you!

**Comment by andrewxhill** [comment] 2021-08-02 15:19
we signed btw, looks like it is waiting for one more.

**Comment by dkkapur** [comment] 2021-08-04 15:49
Actually looks like this went through after @andrewxhill's signature a couple of days ago. @ribasushi @jnthnvctr 
<img width="580" alt="Screen Shot 2021-08-04 at 8 47 29 AM" src="https://user-images.githubusercontent.com/2343218/128212603-ae08aafd-d0bd-4bc1-b097-235a6432be87.png">

**Comment by ribasushi** [comment] 2021-08-05 09:58
@dkkapur confirmed, please close 🎉

**Comment by dkkapur** [comment] 2021-08-05 17:48
@ribasushi keeping this open for your next allocation

**Comment by galen-mcandrew** [comment] 2021-08-23 20:52
@jnthnvctr & @ribasushi , looks like verified client [f1g463yb4ok3lq3tffkvvfmfyngcagpx4kg7c7rei](https://filplus.d.interplanetary.one/clients?filter=f1g463yb4ok3lq3tffkvvfmfyngcagpx4kg7c7rei) still has the full 250TiB of DataCap, and has not yet made deals. 

Wanted to check in and make sure you did not need additional steps from the Fil+ team at this time.

**Comment by jnthnvctr** [comment] 2021-08-23 22:27
No, we've had some hiccups with the tooling which Riba is working through
as he gets capacity.

**Comment by galen-mcandrew** [comment] 2021-09-30 18:52
CLOSING AND ROLLING TO: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/45

**Closed by galen-mcandrew** 2021-09-30 18:52 UTC
Labels: state:Approved

**Comment by filplus-checker** [comment] 2022-12-15 07:31
## DataCap and CID Checker Report[^1]
 - Organization: `Protocol Labs - Filecoin Discover`
 - Client: `f1g463yb4ok3lq3tffkvvfmfyngcagpx4kg7c7rei`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01776264](https://filfox.info/en/address/f01776264) has unknown IP location.

⚠️ [f03000](https://filfox.info/en/address/f03000) has unknown IP location.

| Provider                                                    |                               Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01776264](https://filfox.info/en/address/f01776264)`new`  |                                Unknown |         124.41 TiB |     17.64% |  124.41 TiB |           0.00% |
| [f09848](https://filfox.info/en/address/f09848)             | Rancho Santa Margarita, California, US |          86.52 TiB |     12.27% |   86.52 TiB |           0.00% |
| [f03624](https://filfox.info/en/address/f03624)             |                  Nürnberg, Bavaria, DE |          69.68 TiB |      9.88% |   69.65 TiB |           0.04% |
| [f01611281](https://filfox.info/en/address/f01611281)`new`  |     Hong Kong, Central and Western, HK |          69.57 TiB |      9.87% |   69.57 TiB |           0.00% |
| [f098743](https://filfox.info/en/address/f098743)`new`      |                Shenzhen, Guangdong, CN |          67.87 TiB |      9.62% |   67.77 TiB |           0.14% |
| [f010254](https://filfox.info/en/address/f010254)`new`      |                  Takamatsu, Kagawa, JP |          61.90 TiB |      8.78% |   61.90 TiB |           0.00% |
| [f0417937](https://filfox.info/en/address/f0417937)`new`    |     Hong Kong, Central and Western, HK |          52.71 TiB |      7.47% |   52.71 TiB |           0.00% |
| [f067375](https://filfox.info/en/address/f067375)`new`      |                 Hangzhou, Zhejiang, CN |          48.73 TiB |      6.91% |   48.73 TiB |           0.00% |
| [f054464](https://filfox.info/en/address/f054464)`new`      |     Hong Kong, Central and Western, HK |          30.24 TiB |      4.29% |   30.23 TiB |           0.04% |
| [f01369314](https://filfox.info/en/address/f01369314)`new`  |                Shenzhen, Guangdong, CN |          17.63 TiB |      2.50% |   17.61 TiB |           0.12% |
| [f010491](https://filfox.info/en/address/f010491)`new`      |                Shenzhen, Guangdong, CN |          14.84 TiB |      2.10% |   14.84 TiB |           0.00% |
| [f023467](https://filfox.info/en/address/f023467)           |                         Oslo, Oslo, NO |          13.70 TiB |      1.94% |   13.70 TiB |           0.00% |
| [f0145162](https://filfox.info/en/address/f0145162)         |                  Takamatsu, Kagawa, JP |          13.67 TiB |      1.94% |   13.67 TiB |           0.00% |
| [f019362](https://filfox.info/en/address/f019362)           |                       Wuhan, Hubei, CN |          13.52 TiB |      1.92% |   13.52 TiB |           0.00% |
| [f095334](https://filfox.info/en/address/f095334)`new`      |     Hong Kong, Central and Western, HK |           9.14 TiB |      1.30% |    9.11 TiB |           0.34% |
| [f0397083](https://filfox.info/en/address/f0397083)         |                       Tokyo, Tokyo, JP |           6.95 TiB |      0.99% |    6.95 TiB |           0.00% |
| [f01238](https://filfox.info/en/address/f01238)`new`        |                 Haiphong, Haiphong, VN |           2.05 TiB |      0.29% |    2.05 TiB |           0.00% |
| [f01537511](https://filfox.info/en/address/f01537511)       |           Belgrade, Central Serbia, RS |        1021.50 GiB |      0.14% | 1021.50 GiB |           0.00% |
| [f022352](https://filfox.info/en/address/f022352)           |                         Oslo, Oslo, NO |         766.00 GiB |      0.11% |  766.00 GiB |           0.00% |
| [f0840770](https://filfox.info/en/address/f0840770)         |             University Park, Texas, US |         291.00 GiB |      0.04% |  291.00 GiB |           0.00% |
| [f03000](https://filfox.info/en/address/f03000)             |                                Unknown |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1/1671089484420.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       335.71 TiB |       335.79 TiB |                   1 |          47.62% |
|       138.64 TiB |       277.35 TiB |                   2 |          39.33% |
|        30.66 TiB |        92.02 TiB |                   3 |          13.05% |
|         7.00 GiB |        28.00 GiB |                   4 |           0.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1/1671089485109.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                     | Total Deals Affected | Unique CIDs |         Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | ---------------: |
| [f3vmoie5eprp7hemixg6onrrpmlpsr4frmghlfnxx<br/>7fi3rxbdq4c5enpj7r2qjipxenacaijncq35oldgb<br/>7irq](https://filfox.info/en/address/f3vmoie5eprp7hemixg6onrrpmlpsr4frmghlfnxx7fi3rxbdq4c5enpj7r2qjipxenacaijncq35oldgb7irq) | ``                                                                                                                              |           476.00 GiB |         476 | Philipp Banhardt |
| [f3qxw65gv4fdlptz6n45aw4s6mvanpegjf3zfnsbi<br/>y5ghvuvtortxjmoc2ydrm33t2m2lmpzklkovddw6j<br/>5imq](https://filfox.info/en/address/f3qxw65gv4fdlptz6n45aw4s6mvanpegjf3zfnsbiy5ghvuvtortxjmoc2ydrm33t2m2lmpzklkovddw6j5imq) | ``                                                                                                                              |           475.50 GiB |         478 | Philipp Banhardt |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda)                                                                                                     | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |            10.00 GiB |           2 |        LDN # 293 |
| [f1sxbnukjwf26fjzbmn5js3hblmgj2772wmd4iuoy](https://filfox.info/en/address/f1sxbnukjwf26fjzbmn5js3hblmgj2772wmd4iuoy)                                                                                                     | Unknown                                                                                                                         |             1.00 GiB |           1 |          Unknown |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
