### ISSUE TITLE
[DataCap Application] Genome Ark - Genome Ark DATASET

### ISSUE THREAD

**Issue by guanxinlian** [filecoin-project/filecoin-plus-large-datasets#2146] opened 2023-08-10 06:32 UTC
### Data Owner Name

Genome Ark

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://vertebrategenomesproject.org

### Social Media

```text
https://vertebrategenomesproject.org
```

### Total amount of DataCap being requested

7PiB

### Expected size of single dataset (one copy)

720

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1eubyy3izwwjp6aopl3gvzyndb7c3hw7kyy2o7ty

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Genome Ark hosts genomic information for the Vertebrate Genomes Project (VGP) and other related projects. The VGP is an international collaboration that aims to generate complete and near error-free reference genomes for all extant vertebrate species. These genomes will be used to address fundamental questions in biology and disease, to identify species most genetically at risk for extinction, and to preserve genetic information of life.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The VGP is an international collaboration that aims to generate complete and near error-free reference genomes for all extant vertebrate species. These genomes will be used to address fundamental questions in biology and disease, to identify species most genetically at risk for extinction, and to preserve genetic information of life.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (City and Country)

```text
ZheJiang,China
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I use singularity to prepare the data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
I don't know if this data was uploaded to the Filecoin network
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://genomeark/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
SP ID Entity Location
f02032191 treal Jiaxing,ZheJiang(owner)
f01882219 luo Changsha,Hunan
f01843178 pan Changsha,Hunan
f01172521 llself Changsha,Hunan
f02301 topblocks Santa Clara(US)
f03223 topblocks Santa Clara(US)
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment] 2023-08-10 14:23
- Have you prepared enough token for sector pledge?
- It has been stored before. Why are you choosing to store it again?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1678
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2146.

**Comment by guanxinlian** [comment] 2023-08-10 14:41
> * Have you prepared enough token for sector pledge?
> * It has been stored before. Why are you choosing to store it again?
>   [[DataCap Application] Genome Ark #1678](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1678)
> * Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] Genome Ark - Genome Ark DATASET #2146](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2146).
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

hello @Sunnyiscoming 
I saw that others only wrapped part of the package has been closed, the package is not complete, so I want to go to filecoin above the data storage

I have sent an email to filplus-app-review@fil.org, please check it

**Comment by guanxinlian** [comment] 2023-08-13 01:32
hello @Sunnyiscoming  
Could you take a look at it for me? Thank you very much

**Comment by herrehesse** [comment] 2023-08-14 14:37
@guanxinlian Hello friend! Thank you for opening this LDN.

Can you explain to me why this dataset will add additional value to the ecosystem, it being stored already by other DP's in the past.

Thank you!

**Comment by guanxinlian** [comment] 2023-08-15 00:57
> @guanxinlian Hello friend! Thank you for opening this LDN.
> 
> Can you explain to me why this dataset will add additional value to the ecosystem, it being stored already by other DP's in the past.
> 
> Thank you!

>
Hello
I saw that others only encapsulated part of the data has been closed, the encapsulation is incomplete, so I want to go to the above filecoin for data storage again. Turn it off for me if you don't think so

Thank you

**Comment by herrehesse** [comment] 2023-08-17 06:56
@guanxinlian Since you're not the previous DP and onboarder, it's unclear how you would have access to their index files and know about their incomplete onboarding attempts. Could you please share the method through which you obtained this information? I'm curious to understand.

Thank you.

**Comment by guanxinlian** [comment] 2023-08-17 07:58
> @guanxinlian Since you're not the previous DP and onboarder, it's unclear how you would have access to their index files and know about their incomplete onboarding attempts. Could you please share the method through which you obtained this information? I'm curious to understand.
> 
> Thank you.

hello  Earlier I looked at #1678 as if it was shut down and only stored data on four sp's, but I looked at the open set and saw that the data set was much larger than the one requested by #1678. So I want to get more sp partners involved to do more data set backups

**Comment by Filplus-govteam** [comment] 2023-08-21 14:24
Confirmed as received on registration form:
SPID Entity Location
f02032191 treal Jiaxing,ZheJiang(owner)
f01882219 luo Changsha,Hunan
f01843178 pan Changsha,Hunan
f01172521 llself Changsha,Hunan
f02301 topblocks Santa Clara(US)
f03223 topblocks Santa Clara(US)

**Comment by Sunnyiscoming** [comment] 2023-08-21 14:55
### Datacap Request Trigger
**Total DataCap requested**
> 7PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1eubyy3izwwjp6aopl3gvzyndb7c3hw7kyy2o7ty

**Comment by cryptowhizzard** [comment] 2023-08-21 20:51
Cheers,

Only one remark. f01172521 is a CC miner, no IP adres set on chain, not reachable and cannot be used in Fil+

**Comment by cryptowhizzard** [comment] 2023-08-21 20:55
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4tbgfykdmqhmpxam5uajwqy4jtglp77lhb6w7evhukiqxirckwu 
#### Address 
> f1eubyy3izwwjp6aopl3gvzyndb7c3hw7kyy2o7ty
#### Datacap Allocated
> 358.39TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> d6802b6a-77c9-4f86-8ddc-4f4e63b5ef99
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4tbgfykdmqhmpxam5uajwqy4jtglp77lhb6w7evhukiqxirckwu

**Comment by guanxinlian** [comment] 2023-08-22 00:52
> Cheers,
> 
> Only one remark. f01172521 is a CC miner, no IP adres set on chain, not reachable and cannot be used in Fil+

Ok, I will communicate with this sp partner to open the public ip on the chain
Thank you

**Comment by kernelogic** [comment] 2023-08-28 06:14
Willing to support first round. OP has answered all the questions.

**Comment by kernelogic** [comment] 2023-08-28 06:17
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedswjub3tqvcxviymex6mr6n4kfwpwjvgkxifhp7mqbd6wgnclhxq 
#### Address 
> f1eubyy3izwwjp6aopl3gvzyndb7c3hw7kyy2o7ty
#### Datacap Allocated
> 358.39TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> d6802b6a-77c9-4f86-8ddc-4f4e63b5ef99
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedswjub3tqvcxviymex6mr6n4kfwpwjvgkxifhp7mqbd6wgnclhxq

**Comment by guanxinlian** [comment] 2023-09-16 08:16
keep open

**Comment by guanxinlian** [comment] 2023-09-27 12:42
keep open

**Comment by guanxinlian** [comment] 2023-09-27 12:42
checker:manualTrigger

**Comment by guanxinlian** [comment] 2023-09-28 01:47
checker:manualTrigger

**Comment by guanxinlian** [comment] 2023-09-29 09:09
It is still in the data preparation stage, and the data will be encapsulated in about a week

**Comment by guanxinlian** [comment] 2023-10-10 02:18
checker:manualTrigger

**Comment by guanxinlian** [comment] 2023-10-10 02:25
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

keep open 
We have already started to prepare the packaging work Thank you

**Comment by guanxinlian** [comment] 2023-10-11 02:33
checker:manualTrigger

**Comment by guanxinlian** [comment] 2023-10-11 03:08
The different data I find in aws is also downloaded from different s3 addresses, so why is sharing detected? I'm a little confused

**Comment by guanxinlian** [comment] 2023-10-11 06:34
My client used the wrong wallet to send the order, what should I do in this case, sorry

**Comment by guanxinlian** [comment] 2023-10-22 01:27
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

keep open

**Comment by guanxinlian** [comment] 2023-10-24 08:20
checker:manualTrigger

**Comment by guanxinlian** [comment] 2023-10-26 07:17
checker:manualTrigger

**Comment by kevzak** [comment] 2023-10-27 13:04
SPs taking deals
f02808888 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 36.88 TiB | 34.02% | 36.88 TiB | 0.00%
f03223 | Clifton, New Jersey, USDigitalOcean, LLC | 25.03 TiB | 23.10% | 25.00 TiB | 0.12%
f01969779 | Clifton, New Jersey, USDigitalOcean, LLC | 23.81 TiB | 21.97% | 23.81 TiB | 0.00%
f02301 | Clifton, New Jersey, USDigitalOcean, LLC | 22.66 TiB | 20.91% | 22.66 TiB | 0.00%


SPID Entity Location on Registration form:
f02032191 treal Jiaxing,ZheJiang(owner)
f01882219 luo Changsha,Hunan
f01843178 pan Changsha,Hunan
f01172521 llself Changsha,Hunan
f02301 topblocks Santa Clara(US)
f03223 topblocks Santa Clara(US)

@guanxinlian these SPs are not matching who you said you would store with. Please submit updated list. Closing until then

**Closed by kevzak** 2023-10-27 13:04 UTC
Labels: ready to sign, verified client, very large application, data type: open public

**Comment by guanxinlian** [comment] 2023-10-30 01:23
checker:manualTrigger

**Comment by guanxinlian** [comment] 2023-10-30 01:52
hi @kevzak 
The following is a list of sp packages that I have identified, and several sp partners are currently in active communication and should be added in the future

It seems that there is a problem with the robot recently. I checked my program and there are many sp's that have not been listed, but several sp's have been encapsulated



<html>
<body>


SP ID | Entity | Location
-- | -- | --
f02032191 | treal | ZheJiang
f02808888 | guan | GuangZhou
f02201190 | james | San Jose(US)
f01969779 | nick | Santa Clara(US)
f02301 | topblocks | Santa Clara(US)
f03223 | topblocks | Santa Clara(US)
f02252173 | luna | Tokyo
f02816666 | jastin | Huhehaote
f02808800 | guanxinlian | ZheJiang


</body>
</html>

**Comment by guanxinlian** [comment] 2023-11-03 01:31
Could you open it for me, please @kevzak

**Comment by guanxinlian** [comment] 2023-11-07 12:02
@kevzak @Sunnyiscoming 
Can you help me？
