### ISSUE TITLE
[DataCap Allocation] - The genetic testing data of pet-repulicate （ 1 / 2 ）

### ISSUE THREAD

**Issue by yvonne-23MF** [filecoin-project/filecoin-plus-large-datasets#1121] opened 2022-10-20 09:37 UTC
---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu 23mofang Biotechnology Co., Ltd.
- Website / Social Media: https://www.23mofang.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
- Region: Greater China Region
- Type: Custom Notary
- Identifier: E-fil

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chengdu 23mofang Biotechnology Co., Ltd. was established in March 2015 to provide biogenetic testing and life data analysis services.

According to the "2018 China Genetic Testing Industry Analysis" released by a third-party data agency—Analysys International,23mofang ranked first in the consumer-grade genetic testing field.Here is the news address:https://www.jiemian.com/article/2244613.html

And in In the Forbes list of "Chinese Fifty Most Innovative Companies",23mofang was rated as the "The innovator of Gene testing",check:https://m.huanqiu.com/article/9CaKrnK9GMf。
So far, 23mofang has accumulated 6 rounds of financing from SBCVC,Hanvon technology，Matrix Partners China,CD Capital,etc.23mofang is the largest domestic consumer-based company.

Based on leading genetic research results, 23mofang owns a professional bio-testing center and uses world-leading testing equipment for sequencing, our company provides users with highly readable and usable genetic test reports. 23mofang's self-built genetic testing center has been certified by the National Health and Family Planning Commission and meets all the standards of medical and clinical trial institutions.

For better scientific research,the company also bulid cooperation with Ministry of Education Key Laboratory of Contemporary Anthropology,the Medical Heredity Research Center of Southwest hospital of AMU,Kunming institute of zoology . cas.

23mofang's  pet genetic testing uses saliva to collect  sample and provides hundreds of test items such as pedigree analysis, genetic risk, genetic traits, genetic variant carriage, nutritional needs, medication response, exercise health, skin management and more. we collect and analyze pet genetic data for diagnosing or ruling out the suspected genetic diseases, and predicting the risk of specific diseases, so we can help users to understand the ancestral origin, physical characteristics and health conditions of pets.

Our pet genetic testing helps humans understand animals better and establish a harmonious ecological environment between humans and animals, while the huge pet test analysis data also greatly promotes the development of animal medical research and animal genetic science research.

Offical Website:  https://www.23mofang.com/
Offical Wechat:   23魔方
Offical Tiktok:   @23魔方溯源故事、@23魔方寻宗
```
![image](https://user-images.githubusercontent.com/116244579/196918622-9ba7b820-f2f5-479a-9a2c-cfbcf9c61fc0.png)
![image (1)](https://user-images.githubusercontent.com/116244579/196918787-f3b51b55-74bf-4bce-8c7d-4a77b30d610d.png)
![image (2)](https://user-images.githubusercontent.com/116244579/196918822-54aa2187-acf1-4162-89f9-a2c54bebd689.png)
![image (3)](https://user-images.githubusercontent.com/116244579/196918858-7e140ebc-20a8-454a-b1a8-1325c28c5c17.png)
![e2ebaa67bb3ac873edc4120cac997b6](https://user-images.githubusercontent.com/116244579/196920637-a7272a67-f379-40cf-a952-5a75c05120e3.jpg)

What is the primary source of funding for this project?
```
The fund of data storage in this project is provided by our company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have applied general verification datacap from notaries before, check #427、#428、#602,so we have bulid trust with Filecoin,adn we hope that we can storage our data in Filecoin steady.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Animal gene test samples, analysis results and gene source data. They are all private data.
```

Where was the data in this dataset sourced from?
```
All the data from our company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Parameter indicators of animal data:https://1drv.ms/u/s!Ah-lIf4OzDPabwLnSRrpcnWpidw?e=S0ShEU
List of test samples:https://1drv.ms/u/s!Ah-lIf4OzDPaaoJLZKOAl_D2JTg?e=LXOkdn
Genetic test data:https://1drv.ms/u/s!Ah-lIf4OzDPaa44krWKwYX5v0bA?e=dPctKh
Test result:https://1drv.ms/u/s!Ah-lIf4OzDPabgKczD-K1wnHnh4?e=Alk3MS
Profile of test object:https://1drv.ms/u/s!Ah-lIf4OzDPacDa76kVDEICqZvk?e=bqbJ4e
Test report:https://1drv.ms/u/s!Ah-lIf4OzDPacWPsY8xcDQ8SMLg?e=JHZfPh
 https://1drv.ms/u/s!Ah-lIf4OzDPacvU_l7MwJRrZ154?e=gEaxl6
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
NO
```

What is the expected retrieval frequency for this data?
```
None
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online and off-line
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We currently have an established relationship with MDM, and depending on the subsequent progress of storage and the number of seal, we will continue to investigate and choose a wider range of SPs for cooperation.
We investigate SP from the following two aspects:
--Experience in storing real data
Long-term and stable storage operation and maintenance capabilities.
```

How will you be distributing deals across storage providers?
```
We provide more than 2P of pet genetic data, and copy to 5 duplicates. According to the final SP numbers,we will make a reasonable distribution plan.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, the funds for storage are ready.
```

**Comment by yvonne-23MF** [comment] 2022-10-20 10:15
@kevzak 
Hi，this is our application for FIl-E

**Comment by kevzak** [comment] 2022-10-21 13:19
FYI above @raghavrmadya

**Comment by raghavrmadya** [comment] 2022-10-23 05:44
I've added the label. We can proceed once E-Fil_ multisig is operational

**Comment by NDLABS-OFFICE** [comment] 2022-11-23 07:11
I am very happy to see the submission of the e+fil application. If necessary, please contact me on slack: ND LABS - OFFICE

**Comment by yvonne-23MF** [comment] 2022-11-23 09:48
Thanks for your support. If you have any questions, please contact us,we will actively respond to the review of the WG

**Comment by PluskitOfficial** [comment] 2022-11-25 08:53
@yvonne-23MF 
Willing to support the project. 
But could you please explain the data type and corresponding volume that you plan to store?

**Comment by MRJAVAZHAO** [comment] 2022-11-25 10:36
Hi @yvonne-23MF 
You've done a great job promoting genetic testing.  In the disclosure, you want the data to be stored globally, but you only provide three Chinese nodes .  Do you have any other nodes besides China?

**Comment by yvonne-23MF** [comment] 2022-11-28 09:47
@PluskitOfficial  Thanks for your comments.
The data of pet genetic includes genetic test samples, genetic source data, test reports and pet files.
All data files is divided into three categories: genetic source data, report, and  images, and genetic source data accounts for 99% of these.
The volume of individual pet genetic data exceeds 2GiB and the volume size is determined by the type and range of pets tested.

23 mofang is currently ranked number one in the consumer genetic testing industry, with over 2PiB pet genetic testing data. FYI : https://www.360zhyx.com/home-research-index-rid-70605.shtml

Here is a  complete sample of pet genetic source data , which cannot be opened directly due to its special format, screenshot  for your imformation 
Link: https://drive.google.com/drive/folders/1eBIkIoQPC8RCFY3WntbHK9Ve20HGAoIS?usp=sharing
![data1](https://user-images.githubusercontent.com/116244579/204245623-f75b6798-b748-412d-b40a-85d5b0b850a5.png)
![data2](https://user-images.githubusercontent.com/116244579/204245625-d3e070e8-0d93-45e9-8a01-93fde1042cb5.png)

**Comment by yvonne-23MF** [comment] 2022-11-28 09:56
@MRJAVAZHAO  Thank you for your support.
The SPs we have identified as having been contacted so far are as follows：
SPs in China:
f01943941 
F0150816 (SP explained that the node is migrating due to public policies, and we will update new in time)
SP in Singapore :
f01877862
SP in US:
f01943910
SP in Japan :
f01945296

**Comment by MRJAVAZHAO** [comment] 2022-11-29 02:05
> @MRJAVAZHAO Thank you for your support.
> The SPs we have identified as having been contacted so far are as follows：
> SPs in China:
> f01943941
> F0150816 (SP explained that the node is migrating due to public policies, and we will update new in time)
> SP in Singapore :
> f01877862
> SP in US:
> f01943910
> SP in Japan :
> f01945296



> @MRJAVAZHAO Thank you for your support.
> The SPs we have identified as having been contacted so far are as follows：
> SPs in China:
> f01943941
> F0150816 (SP explained that the node is migrating due to public policies, and we will update new in time)
> SP in Singapore :
> f01877862
> SP in US:
> f01943910
> SP in Japan :
> f01945296

Good

**Comment by MRJAVAZHAO** [comment] 2022-11-29 02:06
> @MRJAVAZHAO Thank you for your support.
> The SPs we have identified as having been contacted so far are as follows：
> SPs in China:
> f01943941
> F0150816 (SP explained that the node is migrating due to public policies, and we will update new in time)
> SP in Singapore :
> f01877862
> SP in US:
> f01943910
> SP in Japan :
> f01945296

Good

**Comment by BlockMakeronline** [comment] 2022-11-29 05:33
Confirm to support the project.

**Comment by yvonne-23MF** [comment] 2022-11-29 06:46
> Confirm to support the project.

@BlockMakeronline  Thank you for your support.

**Comment by yvonne-23MF** [comment] 2022-11-29 06:48
> We need two more E-Fil Notaries to support this application

@kevzak  thank you , kevin
In addition，There is another notary who supports our application in [exception proposal](https://github.com/filecoin-project/notary-governance/issues/634) .Could you confirm it?

**Comment by kevzak** [comment] 2022-11-30 17:21
Hello - I can confirm for the Fil+ team that @yvonne-23MF  has completed the Client Registration and Business Verification Check successfully. 5 Notaries reviewed the business and have shown support for the project. 

Assigned notaries can proceed to review the application and the [Exception Proposal ](https://github.com/filecoin-project/notary-governance/issues/634)

**Comment by kevzak** [comment] 2022-11-30 17:25
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy

**Comment by kevzak** [comment] 2022-11-30 17:26
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy

**Comment by kevzak** [comment] 2022-12-05 15:35
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy

**Comment by PluskitOfficial** [comment] 2022-12-06 01:41
No problem. We'll sign the request later today.

**Comment by xingjitansuo** [comment] 2022-12-06 09:33
@yvonne-23MF 
Please feel free to book my calendar at cabrinahuang@gmail.com for 30-min meeting anytime between 2:00 pm - 5:00 pm 12/7/22, / 12/8/22 so I can get to know more about this project.

**Comment by PluskitOfficial** [comment] 2022-12-06 11:50
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczjdd35lqrbn5yoojm7gygqvns2xetqugxizclnpufkr6rzvbr4o 
#### Address 
> f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> d3af6af5-f575-4e1d-95e4-d4923832c043
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczjdd35lqrbn5yoojm7gygqvns2xetqugxizclnpufkr6rzvbr4o

**Comment by yvonne-23MF** [comment] 2022-12-07 04:58
Hi,@xingjitansuo ,Thank you for your reply. We have confirmed the meeting time with you via email, please check.

![20221207](https://user-images.githubusercontent.com/116244579/206092277-d5bb9bab-81ff-4e1a-a416-8f294ebbe26d.jpg)

**Comment by kevzak** [comment] 2022-12-07 11:25
> > Aborting. Exit Code is Non 0
> 
> @kevzak Hey, KZ, i'm not sure what's going on here. Could you please help to check and confirm whether we need to re-sign again?

It should be OK @PluskitOfficial - this seems to be a bug across many applications. I will let you know.

**Comment by xingjitansuo** [comment] 2022-12-08 07:39
I had a meeting with @yvonne-23MF and did the KYC. I will approve the first round.

**Comment by xingjitansuo** [comment] 2022-12-08 07:49
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3supkvvi4iltl4mgogdhsxg72cbtlkaznuj4lsbcmya2ms3buwk 
#### Address 
> f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> d3af6af5-f575-4e1d-95e4-d4923832c043
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3supkvvi4iltl4mgogdhsxg72cbtlkaznuj4lsbcmya2ms3buwk

**Comment by kevzak** [comment] 2022-12-08 11:47
Hello @yvonne-23MF you have received the first allocation.

Also, when you get a chance can you update us on these questions below so we can learn more?

How do you plan to prepare the dataset?
-IPFS
-lotus
-singularity
-graphsplit
-I don't know
-other/custom tool

How do you plan to make deals to your storage providers?
-Boost Client
-Lotus Client
-Bidbot
-Singularity
-I dont know yet
-Other/custom tool

How will you be distributing your data to storage providers?
-cloud storage (S3)
-HTTP or FTP Server
-IPFS
-Shipping Hard Drives
-Lotus Built-in data transfer
-I don't know yet
-others

**Comment by yvonne-23MF** [comment] 2022-12-12 04:26
Hi, @kevzak This is our reply about storage

How do you plan to prepare the dataset?
-other/custom tool

How do you plan to make deals to your storage providers?
-Lotus Client

How will you be distributing your data to storage providers?
-HTTP or FTP Server
-Shipping Hard Drives

**Comment by kevzak** [comment] 2023-01-12 16:44
@yvonne-23MF 
 just checking in on [your application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1121). You received datacap one month ago. Do you need support with preparation and onboarding?

**Comment by yvonne-23MF** [comment] 2023-01-17 03:52
Hello @kevzak ,
we have been in communication with our service providers and the current situation is as follows.
Firstly, we are still actively contacting more SPs in order to better comply with Fil+'s decentralized guidelines.
Secondly, as the service providers we have contacted have chosen nodes scattered all over the world, with some of the SP server rooms located overseas, our data needs to be transferred online and the data is still being transferred.
In addition, it is the Spring Festival holiday in China, and the Chinese service provider we cooperated with may be out of office.
Therefore,we decided to seal until all SPs receive the data, and they will synchronously sealing sector and strictly comply with the DC allocation and CID retrieval requirements.
We expect to officially start sealing in February.

**Comment by kevzak** [comment] 2023-02-27 14:35
Hi @yvonne-23MF just checking in, need any support?

**Comment by yvonne-23MF** [comment] 2023-03-02 08:01
Hello @kevzak 
Thanks for your reminding.We've already started storing.Everything is going well so far.

**Comment by yvonne-23MF** [comment] 2023-03-06 03:36
Hi @kevzak 
Our allocation has been  exhausted. What  we can do to facilitate the next step.

**Comment by kevzak** [comment] 2023-03-06 14:16
We'll move forward following the updated Notary SLA https://github.com/filecoin-project/notary-governance/discussions/807 and randomly assign:

@Fenbushi-Filecoin
@bmcnabb25


Please review the application details for the Client, Data, and SPs and leave a comment. Please leave a comment by March 8th.

**Comment by kevzak** [comment] 2023-03-06 14:24
> Hi @kevzak Our allocation has been exhausted. What we can do to facilitate the next step.

@yvonne-23MF - as guidance, I recommend that you should provide an update for Notaries about your SP usage so far so they can understand. If the SPs used do not match your list, why not? Why only one SP used so far?

**Comment by yvonne-23MF** [comment] 2023-03-07 04:54
@kevzak Thanks for your work.
1. In the process of project application, some sp withdrew from the project, and we contacted new ones. We will pay attention to timely update in the comments.
f01945296 temporarily adjusted, has been withdrawn from the project.
The latest sp info is disclosed as follows:

| SP ID | SP org | SP region |
| --- | --- | --- |
| f0442671 | zhongliang | HK | 
| f02031264 | MDM | SGP | 

2. During the early allocation phase, each sp cannot be synchronized due to different network conditions and encapsulation capabilities.
As the allocation increases, most sp will catch up, bringing the overall distribution into compliance.

**Comment by kevzak** [comment] 2023-03-08 14:11
Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@TakiChain
@Meibuy


Leave a comment as needed. Please comment by March 10th. Thanks! If you are not interested in signing please also leave a comment stating why.

**Comment by yvonne-23MF** [comment] 2023-03-10 07:29
@[TakiChain](https://github.com/TakiChain) @[Meibuy](https://github.com/Meibuy)
Please review our application , many thanks .

**Comment by yvonne-23MF** [comment] 2023-03-13 16:17
@kevzak Will there be a new random allocation triggered today?

**Comment by kevzak** [comment] 2023-03-13 16:25
Hello @TakiChain @Meibuy We did not hear from you. 

Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@swatchliu
@BlockMakeronline

Please leave a comment as needed. Please comment by March 15th. Thanks! If you are not interested in signing please also leave a comment stating why.

**Comment by BlockMakeronline** [comment] 2023-03-14 01:36
checker:manualTrigger

**Comment by BlockMakeronline** [comment] 2023-03-14 01:46
Is there any more sps you will cooperate with? Can you list them here?

**Comment by yvonne-23MF** [comment] 2023-03-14 06:35
@BlockMakeronline Thanks for the timely review.  
Currently, the SPs we have been in contact with are gradually on boarding.

| SP ID | SP org | SP region |
| --- | --- | --- |
| f0442671 | zhongliang | HK | 
| f02031264 | MDM | SGP |           
| f02051757 | CCR AutoBAn  | QGB  | 
| f02048808 | CCR AutoBAn | QGB  | 
| f02032453 | TAHALUF AL EMARAT TECHNICAL SOLUTIONS L.L.C  | UAE  |

**Comment by BlockMakeronline** [comment] 2023-03-14 07:51
Datacap distribution is limited in 2 sps now. It is not ok.
But if you can solve this problem in the next round. I will approve you.

**Comment by swatchliu** [comment] 2023-03-15 05:46
![image](https://user-images.githubusercontent.com/46444977/225217992-f7c6cde6-e1cf-4c77-af0b-b487e553490a.png)

Could you help to explain it and show a better resulit in the next round?

**Comment by yvonne-23MF** [comment] 2023-03-15 06:33
@swatchliu 
Yes.Currently, we have only started encapsulating for one node.   Because the first batch has a smaller allocation, and the preparation work of other storage providers has not been completed yet, Therefore, the current dataset is concentrated on one node.
Based on the results of our communication with all storage providers, they are already progressing with device procurement, data center contracting, and encapsulating machine allocation, and everything is normal.
We guarantee that in the later encapsulating process, we will strictly follow the community's allocation rules for encapsulating, but the startup of nodes may have a sequential process.  The second batch of shares should be encapsulated on no less than two nodes.

**Comment by swatchliu** [comment] 2023-03-15 07:26
OK, willing to support!

**Comment by kevzak** [comment] 2023-03-15 18:18
Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@stcloudlisa
@MRJAVAZHAO

Please leave a comment as needed. Please comment by March 17th. Thanks! If you are not interested in signing please also leave a comment stating why.

**Comment by BlockMakeronline** [comment] 2023-03-16 01:55
I failed to approve this issue for some mistake happened during approving.

**Comment by techgood123** [comment] 2023-03-16 02:30
This doesn't seem to fit the rules, since you're giving the DC all to one SP. However, this is FIL-E, not FIL+, and FIL-E has its own rules.

Today, we need to find the rules of FIL-E and discuss them. I will wait for the answer until 18:00 this afternoon. I hope the community will reply.

If there is no objection, I may temporarily support clients

**Comment by stcouldlisa** [comment] 2023-03-16 07:59
<img width="437" alt="WX20230316-155851@2x" src="https://user-images.githubusercontent.com/112812896/225551811-10421ccb-97fd-4a36-8963-d84240549df4.png">

**Comment by stcouldlisa** [comment] 2023-03-16 08:06
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsdlbb4caolapfcglb43s5sjwjou6ggahunw6qwnf2uqra4gc7xi 
#### Address 
> f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> f21a592f-2b7a-47f7-9b76-0a452956fbaf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsdlbb4caolapfcglb43s5sjwjou6ggahunw6qwnf2uqra4gc7xi

**Comment by stcouldlisa** [comment] 2023-03-16 08:09
I will pay attention to the next cid report

**Comment by yvonne-23MF** [comment] 2023-03-27 10:37
Hi @kevzak @simonkim0515 @fabriziogianni7 
More than 80% of the prior DataCap allocation has been used up, please help trigger the next round of allocation.

**Comment by kevzak** [comment] 2023-03-29 18:33
Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@derricktan23
@liyunzhi-666

Please leave a comment as needed. Please comment by April 1st. Thanks! If you are not interested in signing please also leave a comment stating why.

**Comment by liyunzhi-666** [comment] 2023-03-30 02:30
checker:manualTrigger

**Comment by liyunzhi-666** [comment] 2023-03-30 02:39
Hi @yvonne-23MF , can you explain about the two warnings? And can we see better results in the next round?
![image](https://user-images.githubusercontent.com/52949274/228714046-c082688f-34c1-429c-87e6-8f16fcb9b64c.png)

**Comment by yvonne-23MF** [comment] 2023-03-30 02:45
@liyunzhi-666 thanks for your asking.
The reported results are reasonable because different service providers have different speeds. From the comparison of two reports, the distribution situation has significantly improved. The service providers we contacted are also gradually joining and will participate in the upcoming work step by step.
f02032453 DU
f01986314 HK 
f0150816 CN 
f0119828 HK 
f02048808 Br 
f02051757 Br

**Comment by derricktan23** [comment] 2023-03-30 07:20
hi @liyunzhi-666 
Considering the variability of speed among different service providers, the results are reasonable, It's encouraging to hear that the distribution situation shall improve significantly.  

The client data files are able to retrieved by CID. Willing to support the application, hope to see more improvements next round as promosed. 

![image](https://user-images.githubusercontent.com/108317502/228759433-18a571d9-0dd9-4092-94a8-1eace35e1031.png)

**Comment by Tom-OriginStorage** [comment] 2023-03-30 07:52
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakx3aw4bfxvtdgfjysuq6fuyony42bz76ebrtt3mpbqbnuq6hl3a 
#### Address 
> f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 24980cfe-2c8d-461e-bb67-365e6cad8aeb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakx3aw4bfxvtdgfjysuq6fuyony42bz76ebrtt3mpbqbnuq6hl3a

**Comment by liyunzhi-666** [comment] 2023-03-30 09:07
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpjm3wkch2fj2zlev4vl4bfyxmq56rd77esfgfcggo2x3swr4jdy 
#### Address 
> f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpjm3wkch2fj2zlev4vl4bfyxmq56rd77esfgfcggo2x3swr4jdy

**Comment by kevzak** [comment] 2023-05-15 12:53
checker:manualTrigger

**Comment by yvonne-23MF** [comment] 2023-05-16 03:26
Thanks, Kevin.
Appreciate your prompt attention and question.
Yes, since applying for the project in Oct last year, we have looked for many service providers, and eventually the SPs who participated in the packaging and persisted until the completion of the project needed to meet the following conditions:
- Package according to FIL+ storage rules
- Have devices and data ready
- Accept the waiting time allocated by DC (the longer the waiting time, the higher the packaging cost, which may cause SPs to withdraw midway) 
Currently, the SPs participating in storage are as follows: 
f02048808 BR 
f02032453 AE 
f02052252 US

**Comment by NiwanDao** [comment] 2023-05-16 08:57
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecl5ktsynummorxfxn4d57sijofmjic4a653egx2ty7wifpdoice6 
#### Address 
> f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> b6a5eeaa-9b48-4f96-b417-2220c82e1750
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecl5ktsynummorxfxn4d57sijofmjic4a653egx2ty7wifpdoice6

**Comment by stcouldlisa** [comment] 2023-05-16 10:15
Looks like a pretty good improvement，willing to support

**Comment by stcouldlisa** [comment] 2023-05-16 10:17
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6arpf6vxvj3qsoslj7iztpbfs7w5m3nk2ehlb6laa5rytryny3y 
#### Address 
> f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> b6a5eeaa-9b48-4f96-b417-2220c82e1750
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6arpf6vxvj3qsoslj7iztpbfs7w5m3nk2ehlb6laa5rytryny3y

**Comment by yvonne-23MF** [comment] 2023-05-29 02:01
Status update:Data transfer is currently in progress.

**Comment by yvonne-23MF** [comment] 2023-06-05 03:30
Update: Everything is normal.

**Comment by yvonne-23MF** [comment] 2023-06-14 02:26
Status update:Data transfer is currently in progress.

**Comment by yvonne-23MF** [comment] 2023-06-26 09:42
Update: data preparation phase

**Comment by kevzak** [comment] 2023-07-03 13:43
Hello @yvonne-23MF we have a new KYC ID check available on [filplus.storage](https://filplus.storage/). Please complete when you have a chance as a requirement for E-Fil+ to add additional layer of trust and to verify this GitHub account. See details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

**Comment by yvonne-23MF** [comment] 2023-07-24 03:29
Okay, we got it and will deal with it  soon

**Comment by data-programs** [comment] 2023-08-03 12:00
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by yvonne-23MF** [comment] 2023-08-14 02:39
Update

**Comment by yvonne-23MF** [comment] 2023-08-25 07:03
update

**Comment by yvonne-23MF** [comment] 2023-09-05 03:49
Please keep it open

**Comment by yvonne-23MF** [comment] 2023-09-14 08:01
Please keep it open

**Comment by yvonne-23MF** [comment] 2023-09-25 02:00
update

**Comment by yvonne-23MF** [comment] 2023-10-04 03:16
update

**Comment by yvonne-23MF** [comment] 2023-10-16 02:59
update

**Comment by yvonne-23MF** [comment] 2023-10-25 09:26
update

**Comment by yvonne-23MF** [comment] 2023-11-03 01:57
update

**Comment by yvonne-23MF** [comment] 2023-11-13 06:00
update

**Comment by herrehesse** [comment] 2023-11-14 09:09
checker:manualTrigger

**Comment by herrehesse** [comment] 2023-11-14 09:11
![Screenshot 2023-11-14 at 10 11 22](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/6a0702f0-9efa-49f0-8e72-407e7ae84f81)

Beautiful example of 100% fully self-dealing with VPN abuse.
Close this LDN immediately @kevzak

**Comment by Sunnyiscoming** [comment] 2023-11-18 14:10
Hello, @yvonne-23MF per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment] 2023-11-21 14:26
SPs initially provided:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1121#issuecomment-1328808120
SPs in China:
f01943941
F0150816 (SP explained that the node is migrating due to public policies, and we will update new in time)
SP in Singapore :
f01877862
SP in US:
f01943910
SP in Japan :
f01945296

SPs taking deals:

f02032453new | Abu Dhabi, Abu Dhabi, AEAmazon.com, Inc. | 288.56 TiB | 22.32% | 288.56 TiB | 0.00%
f02048808new | São Paulo, São Paulo, BRAmazon.com, Inc. | 286.56 TiB | 22.16% | 286.56 TiB | 0.00%
f02052252new | Boardman, Oregon, USAmazon.com, Inc. | 286.13 TiB | 22.13% | 286.13 TiB | 0.00%
f02031264new | Singapore, Singapore, SGAmazon.com, Inc. | 199.75 TiB | 15.45% | 199.75 TiB | 0.00%
f02058976 | Sydney, New South Wales, AUAmazon.com, Inc. | 131.88 TiB | 10.20% | 131.88 TiB | 0.00%
f0442671 | Hong Kong, Central and Western, HKAmazon.com, Inc. | 99.94 TiB | 7.73% | 99.94 TiB | 0.00%
f01945296 | Tokyo, Tokyo, JPAmazon.com, Inc. | 64.00 GiB | 0.00% | 64.00 GiB | 0.00%

SPs not matching as planned. @yvonne-23MF closing until a complete list of entities and distribution is provided

**Closed by Filplus-govteam** 2023-11-21 14:26 UTC
Labels: efil+, verified client, granted, kyc verified
